import { createClient } from 'npm:@supabase/supabase-js@2.95.0'
type Row=Record<string,unknown>
const headers={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS'}
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body,null,2),{status,headers:{...headers,'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'}})
function envKey(jsonName:string,fallbackName:string){const raw=Deno.env.get(jsonName);if(raw){try{const p=JSON.parse(raw);if(p?.default)return String(p.default)}catch{}}return Deno.env.get(fallbackName)??''}
Deno.serve(async(req:Request)=>{
 if(req.method==='OPTIONS')return new Response('ok',{headers});if(req.method!=='POST')return json({error:'Método no permitido.'},405)
 try{
  const url=Deno.env.get('SUPABASE_URL')??'',publishable=envKey('SUPABASE_PUBLISHABLE_KEYS','SUPABASE_ANON_KEY'),secret=envKey('SUPABASE_SECRET_KEYS','SUPABASE_SERVICE_ROLE_KEY');if(!url||!publishable||!secret)return json({error:'Configuración del servidor incompleta.'},500)
  const authHeader=req.headers.get('Authorization')??'',token=authHeader.startsWith('Bearer ')?authHeader.slice(7):'';if(!token)return json({error:'Sesión requerida.'},401)
  const userClient=createClient(url,publishable,{global:{headers:{Authorization:authHeader}},auth:{persistSession:false,autoRefreshToken:false}});const{data:auth,error:authError}=await userClient.auth.getUser(token);const user=auth?.user;if(authError||!user)return json({error:'Sesión no válida.'},401)
  const admin=createClient(url,secret,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}}),body=await req.json().catch(()=>({}));if(String(body?.action||'export')!=='export')return json({error:'Acción no válida.'},400)
  const all=async(table:string,select:string,filter:(q:any)=>any)=>{const out:Row[]=[];let from=0;for(let page=0;page<50;page++){let q=admin.from(table).select(select).range(from,from+999);q=filter(q);const{data,error}=await q;if(error){console.error(table,error.message);return{rows:out,error:error.message}}const rows=(data||[]) as Row[];out.push(...rows);if(rows.length<1000)break;from+=1000}return{rows:out,error:null}}
  const uid=user.id,profile=(await admin.from('tedvio_user_profiles').select('email,full_name,role,status,plan,last_sign_in_at,created_at,updated_at').eq('user_id',uid).maybeSingle()).data||null
  const memberships=(await all('tedvio_institution_memberships','institution_id,member_role,status,created_at,updated_at',q=>q.eq('user_id',uid))).rows,instIds=memberships.map((x:any)=>x.institution_id).filter(Boolean)
  const institutions=instIds.length?(await admin.from('tedvio_institutions').select('id,name,slug,status,plan,report_display_name,report_title,report_approver_name,report_approver_title,report_approval_label,report_document_code').in('id',instIds)).data||[]:[]
  const universities=(await all('v2_universities','id,name,created_at',q=>q.eq('teacher_id',uid))).rows,programs=(await all('v2_programs','id,university_id,name,created_at',q=>q.eq('teacher_id',uid))).rows,groups=(await all('v2_groups','id,program_id,name,group_name,subject,term,school_cycle,university,program,is_demo,created_at',q=>q.eq('teacher_id',uid))).rows,students=(await all('v2_group_students','id,group_id,enrollment,full_name,active,created_at',q=>q.eq('teacher_id',uid))).rows
  const attendanceSessions=(await all('v2_attendance_sessions','id,group_id,attendance_date,notes,status,opened_at,paused_at,closed_at,late_after_minutes,auto_mark_absent,created_at,updated_at',q=>q.eq('teacher_id',uid))).rows,attendanceRecords=(await all('v2_attendance_records','id,attendance_session_id,student_id,status,note,observation,updated_at',q=>q.eq('teacher_id',uid))).rows
  const liveSessions=(await all('v2_sessions','id,code,title,status,competitive,team_mode,created_at,started_at,closed_at,university,educational_program,group_name,group_id,scoring_mode,speed_bonus,streak_bonus,randomize_questions,randomize_options,roster_required,is_demo',q=>q.eq('teacher_id',uid))).rows,sessionIds=liveSessions.map((x:any)=>x.id)
  const questions=sessionIds.length?(await all('v2_questions','id,session_id,bank_id,position,prompt,question_type,options,correct_answer,media_url,media_type,timer_seconds,status,launched_at,closed_at,explanation,difficulty',q=>q.in('session_id',sessionIds))).rows:[],participants=sessionIds.length?(await all('v2_participants','id,session_id,display_name,team_name,joined_at,last_seen_at,roster_student_id,matricula',q=>q.in('session_id',sessionIds))).rows:[],participantIds=participants.map((x:any)=>x.id),responses=participantIds.length?(await all('v2_responses','id,question_id,participant_id,answer,submitted_at,is_correct,points,streak',q=>q.in('participant_id',participantIds))).rows:[]
  const bank=(await all('v2_question_bank','id,title,subject,topic,question_type,prompt,options,correct_answer,media_url,media_type,created_at,updated_at,explanation,difficulty,folder,tags,bloom,favorite,archived',q=>q.eq('teacher_id',uid))).rows
  const assignments=(await all('v2_assignments','id,group_id,code,title,instructions,status,opens_at,closes_at,max_attempts,time_limit_minutes,random_question_count,shuffle_questions,shuffle_options,feedback_mode,allow_late,created_at,updated_at',q=>q.eq('teacher_id',uid))).rows,assignmentIds=assignments.map((x:any)=>x.id),assignmentItems=assignmentIds.length?(await all('v2_assignment_items','id,assignment_id,bank_id,position,points,prompt,question_type,options,correct_answer,explanation,difficulty,media_url,media_type,created_at',q=>q.in('assignment_id',assignmentIds))).rows:[],attempts=assignmentIds.length?(await all('v2_assignment_attempts','id,assignment_id,group_student_id,display_name,enrollment,attempt_no,status,started_at,expires_at,submitted_at,auto_submitted,late,score,max_score,percentage',q=>q.in('assignment_id',assignmentIds))).rows:[],attemptIds=attempts.map((x:any)=>x.id),assignmentResponses=attemptIds.length?(await all('v2_assignment_responses','id,attempt_id,assignment_item_id,answer,is_correct,points,answered_at,updated_at',q=>q.in('attempt_id',attemptIds))).rows:[]
  const gradeCategories=(await all('v2_grade_categories','id,group_id,name,kind,weight,created_at',q=>q.eq('teacher_id',uid))).rows,gradeItems=(await all('v2_grade_items','id,group_id,category_id,title,max_score,item_date,created_at',q=>q.eq('teacher_id',uid))).rows,gradeScores=(await all('v2_grade_scores','id,item_id,student_id,score,note,updated_at',q=>q.eq('teacher_id',uid))).rows,paperExams=(await all('v2_paper_exams','id,group_id,title,subject,question_count,option_count,versions,created_at,updated_at',q=>q.eq('teacher_id',uid))).rows,paperResults=(await all('v2_paper_exam_results','id,exam_id,student_id,enrollment,student_name,version,answers,correct_count,blank_count,score,reviewed,created_at,updated_at',q=>q.eq('teacher_id',uid))).rows,notes=(await all('v2_student_notes','id,group_id,student_id,note,updated_at',q=>q.eq('teacher_id',uid))).rows
  const consents=(await all('tedvio_user_consents','document_key,document_version,accepted_at,source',q=>q.eq('user_id',uid))).rows,deletionRequests=(await all('tedvio_account_deletion_requests','status,reason,requested_at,scheduled_for,cancelled_at,completed_at,updated_at',q=>q.eq('user_id',uid))).rows,exportAudit=(await all('tedvio_data_export_audit','format,status,requested_at,completed_at',q=>q.eq('user_id',uid))).rows
  await admin.from('tedvio_data_export_audit').insert({user_id:uid,format:'json',status:'completed',requested_at:new Date().toISOString(),completed_at:new Date().toISOString()})
  return json({export:{product:'TEDVIO',version:'69',generated_at:new Date().toISOString(),format:'application/json',notice:'Este archivo contiene datos asociados a la cuenta docente. No incluye contraseñas, sesiones de autenticación ni tokens privados.'},account:{id:uid,email:user.email??null,created_at:user.created_at,last_sign_in_at:user.last_sign_in_at,full_name:user.user_metadata?.full_name??user.user_metadata?.name??null,profile},institutions:{memberships,institutions},academics:{universities,programs,groups,students},attendance:{sessions:attendanceSessions,records:attendanceRecords},live:{sessions:liveSessions,questions,participants,responses},question_bank:bank,assignments:{assignments,items:assignmentItems,attempts,responses:assignmentResponses},gradebook:{categories:gradeCategories,items:gradeItems,scores:gradeScores},paper_exams:{exams:paperExams,results:paperResults},student_notes:notes,privacy:{consents,deletion_requests:deletionRequests,export_history:exportAudit}})
 }catch(error){console.error('tedvio-account-v69',error);return json({error:error instanceof Error?error.message:'No se pudo exportar la cuenta.'},500)}
})