version: 2
updates:
  - package-ecosystem: npm
    directory: /apps/teacher-v2
    schedule:
      interval: weekly
      day: monday
      time: '09:00'
      timezone: America/Mexico_City
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - security
    commit-message:
      prefix: deps
    groups:
      production-dependencies:
        dependency-type: production
        update-types:
          - patch
          - minor
      development-dependencies:
        dependency-type: development
        update-types:
          - patch
          - minor
