import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const c=window.TEDVIO_CONFIG||{},sb=createClient(c.SUPABASE_URL,c.SUPABASE_PUBLISHABLE_KEY),app=document.querySelector('#app');
const S={session:null,participant:null,question:null,responses:[],channel:null,view:'live',bank:[],volume:.65,muted:false,timerSeconds:30,timer:null,remaining:0,presentation:false};
const logo=(full=false)=>full?`<div style="display:flex;flex-direction:column;align-items:center;justify-content:center;gap:10px;margin:0 auto 20px"><img src="./assets/tedvio_isotipo_1024.png" alt="TEDVIO" style="width:84px;height:84px;object-fit:contain;display:block"><div style="font-size:30px;line-height:1;font-weight:900;letter-spacing:.08em;color:#0A1B3D">TEDVIO</div></div>`:`<img src="./assets/tedvio_isotipo_1024.png" alt="TEDVIO" style="width:50px;height:50px;object-fit:contain;display:block">`;
const code=()=>String(Math.floor(100000+Math.random()*900000));
function go(r){location.hash=r;render()}window.go=go;
let audioCtx;
function ctx(){return audioCtx||(audioCtx=new(window.AudioContext||window.webkitAudioContext)())}
function tone(f,t,d,v=.18,type='sine'){if(S.muted)return;const a=ctx(),o=a.createOscillator(),g=a.createGain();o.type=type;o.frequency.setValueAtTime(f,a.currentTime+t);g.gain.setValueAtTime(0,a.currentTime+t);g.gain.linearRampToValueAtTime(v*S.volume,a.currentTime+t+.015);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+t+d);o.connect(g);g.connect(a.destination);o.start(a.currentTime+t);o.stop(a.currentTime+t+d+.02)}
function sound(k){if(k==='applause'){for(let i=0;i<18;i++)tone(900+Math.random()*1300,i*.045,.07,.08,'square')}if(k==='celebrate'){[523,659,784,1047].forEach((f,i)=>tone(f,i*.09,.28,.18,'triangle'))}if(k==='oh'){[330,294,262,220].forEach((f,i)=>tone(f,i*.11,.3,.15,'sine'))}if(k==='drum'){[110,95,80,70].forEach((f,i)=>tone(f,i*.13,.18,.28,'sawtooth'))}if(k==='attention'){tone(880,0,.16,.2);tone(1175,.2,.22,.2)}}
window.sound=sound;window.setVolume=v=>{S.volume=Number(v)};window.toggleMute=()=>{S.muted=!S.muted;render()};
function stopTimer(){if(S.timer){clearInterval(S.timer);S.timer=null}}
async function startTimer(){stopTimer();if(!S.question||S.question.status!=='live')return alert('Primero lanza una pregunta.');S.remaining=S.timerSeconds;render();S.timer=setInterval(async()=>{S.remaining-=1;if(S.remaining<=0){S.remaining=0;stopTimer();await closeQuestion();return}render()},1000)}
function setTimerSeconds(v){S.timerSeconds=Number(v);S.remaining=0;stopTimer();render()}
function togglePresentation(){S.presentation=!S.presentation;document.body.classList.toggle('tedvio-presentation',S.presentation);render()}
window.startTimer=startTimer;window.stopTimer=()=>{stopTimer();S.remaining=0;render()};window.setTimerSeconds=setTimerSeconds;window.togglePresentation=togglePresentation;
const presentationStyle=document.createElement('style');presentationStyle.textContent=`body.tedvio-presentation .topbar-actions,body.tedvio-presentation .hero .btn,body.tedvio-presentation .teacher-tools,body.tedvio-presentation .sound-card{display:none!important}body.tedvio-presentation .content{max-width:1440px;margin:0 auto}body.tedvio-presentation .card{font-size:1.12em}body.tedvio-presentation .session-panel{transform:scale(1.02);transform-origin:top center}`;document.head.appendChild(presentationStyle);
function drawQR(){if(!S.session||typeof QRCode==='undefined')return;const el=document.querySelector('#joinQR');if(!el)return;el.innerHTML='';new QRCode(el,{text:`${location.origin}/#join?code=${S.session.code}`,width:190,height:190,correctLevel:QRCode.CorrectLevel.M})}
async function createSession(){let data,error;for(let i=0;i<5;i++){({data,error}=await sb.from('sessions').insert({code:code(),title:'Mi clase TEDVIO',status:'draft'}).select().single());if(!error)break}if(error)return alert(error.message);S.session=data;subscribe();render()}window.createSession=createSession;
async function joinSession(){const x=document.querySelector('#code').value.trim(),n=document.querySelector('#name').value.trim();if(!n)return alert('Escribe tu nombre');const {data:s}=await sb.from('sessions').select('*').eq('code',x).neq('status','closed').maybeSingle();if(!s)return alert('Código no válido');const {data:p,error}=await sb.from('participants').insert({session_id:s.id,display_name:n}).select().single();if(error)return alert(error.message);S.session=s;S.participant=p;subscribe();await refresh();go('student')}window.joinSession=joinSession;
async function loadBank(){const {data}=await sb.from('question_bank').select('*').order('created_at',{ascending:false});S.bank=data||[]}
async function showBank(){await loadBank();S.view='bank';render()}window.showBank=showBank;
function showLive(){S.view='live';render()}window.showLive=showLive;
function showCreate(){S.view='create';render()}window.showCreate=showCreate;
async function saveBank(){const prompt=document.querySelector('#bp').value.trim(),subject=document.querySelector('#bs').value.trim(),topic=document.querySelector('#bt').value.trim(),opts=[0,1,2,3].map(i=>document.querySelector('#bo'+i).value.trim()),correct=document.querySelector('input[name=bc]:checked')?.value;if(!prompt||opts.some(x=>!x)||correct==null)return alert('Completa la pregunta, opciones y respuesta correcta');const {error}=await sb.from('question_bank').insert({title:prompt.slice(0,80),subject,topic,question_type:'multiple_choice',prompt,options:opts,correct_answer:correct});if(error)return alert(error.message);await loadBank();S.view='bank';render()}window.saveBank=saveBank;
async function launchBank(id){const q=S.bank.find(x=>x.id===id);if(!q||!S.session)return;const {data:last}=await sb.from('questions').select('position').eq('session_id',S.session.id).order('position',{ascending:false}).limit(1),pos=(last?.[0]?.position||0)+1;const {data:newq,error}=await sb.from('questions').insert({session_id:S.session.id,position:pos,prompt:q.prompt,question_type:q.question_type,options:q.options,correct_answer:q.correct_answer,status:'live',launched_at:new Date().toISOString()}).select().single();if(error)return alert(error.message);await sb.from('sessions').update({current_question_id:newq.id,status:'live',started_at:new Date().toISOString()}).eq('id',S.session.id);S.question=newq;S.responses=[];S.view='live';S.remaining=0;stopTimer();await refresh()}window.launchBank=launchBank;
async function deleteBank(id){if(!confirm('¿Eliminar esta pregunta guardada?'))return;await sb.from('question_bank').delete().eq('id',id);await loadBank();render()}window.deleteBank=deleteBank;
async function closeQuestion(){if(!S.question)return;stopTimer();await sb.from('questions').update({status:'closed',closed_at:new Date().toISOString()}).eq('id',S.question.id);await refresh()}window.closeQuestion=closeQuestion;
async function revealAnswer(){if(!S.question)return;stopTimer();await sb.from('questions').update({status:'revealed'}).eq('id',S.question.id);await refresh()}window.revealAnswer=revealAnswer;
async function endSession(){if(!confirm('¿Finalizar la sesión?'))return;stopTimer();document.body.classList.remove('tedvio-presentation');S.presentation=false;await sb.from('sessions').update({status:'closed',closed_at:new Date().toISOString()}).eq('id',S.session.id);S.session=null;S.question=null;S.remaining=0;render()}window.endSession=endSession;
async function sendAnswer(i){if(!S.participant||!S.question||S.question.status!=='live')return;const {error}=await sb.from('responses').insert({question_id:S.question.id,participant_id:S.participant.id,answer:String(i)});if(error&&error.code!=='23505')return alert(error.message);document.querySelector('.mobile-body').innerHTML=`<div style="text-align:center;padding-top:70px">${logo()}<div style="font-size:64px">✓</div><h1>¡Respuesta enviada!</h1><p>Espera los resultados.</p></div>`}window.sendAnswer=sendAnswer;
async function refresh(){if(!S.session)return;const {data:s}=await sb.from('sessions').select('*').eq('id',S.session.id).single();S.session=s||S.session;if(S.session.current_question_id){const {data:q}=await sb.from('questions').select('*').eq('id',S.session.current_question_id).maybeSingle();S.question=q;const {data:r}=await sb.from('responses').select('*').eq('question_id',S.session.current_question_id);S.responses=r||[]}render()}
function subscribe(){if(S.channel)sb.removeChannel(S.channel);S.channel=sb.channel('tedvio-'+S.session.id).on('postgres_changes',{event:'*',schema:'public',table:'sessions',filter:`id=eq.${S.session.id}`},refresh).on('postgres_changes',{event:'*',schema:'public',table:'participants',filter:`session_id=eq.${S.session.id}`},refresh).on('postgres_changes',{event:'*',schema:'public',table:'questions',filter:`session_id=eq.${S.session.id}`},refresh).on('postgres_changes',{event:'*',schema:'public',table:'responses'},refresh).subscribe()}
function soundPanel(){return `<div class="card sound-card" style="margin-top:18px"><div style="display:flex;justify-content:space-between;align-items:center;gap:12px"><div><h3 style="margin:0">🔊 Efectos de clase</h3><small>Se reproducen en el equipo del profesor</small></div><button class="btn secondary" onclick="toggleMute()">${S.muted?'🔇 Activar':'🔊 Silenciar'}</button></div><div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:14px"><button class="btn secondary" onclick="sound('applause')">👏 Aplausos</button><button class="btn secondary" onclick="sound('celebrate')">🎉 Celebración</button><button class="btn secondary" onclick="sound('oh')">😬 Ohhh</button><button class="btn secondary" onclick="sound('drum')">🥁 Redoble</button><button class="btn secondary" onclick="sound('attention')">🔔 Atención</button></div><div style="margin-top:14px"><label>Volumen</label><input type="range" min="0" max="1" step="0.05" value="${S.volume}" oninput="setVolume(this.value)" style="width:100%"></div></div>`}
function timerPanel(){return `<div class="card teacher-tools" style="margin-top:18px"><div style="display:flex;justify-content:space-between;align-items:center;gap:12px;flex-wrap:wrap"><div><h3 style="margin:0">⏱ Temporizador</h3><small>Al llegar a cero se cierran las respuestas.</small></div><div style="font-size:34px;font-weight:900">${S.remaining>0?S.remaining+' s':'—'}</div></div><div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:14px"><select onchange="setTimerSeconds(this.value)" style="padding:10px;border-radius:10px"><option value="15" ${S.timerSeconds===15?'selected':''}>15 s</option><option value="30" ${S.timerSeconds===30?'selected':''}>30 s</option><option value="45" ${S.timerSeconds===45?'selected':''}>45 s</option><option value="60" ${S.timerSeconds===60?'selected':''}>60 s</option><option value="90" ${S.timerSeconds===90?'selected':''}>90 s</option></select><button class="btn primary" onclick="startTimer()">Iniciar</button><button class="btn secondary" onclick="stopTimer()">Detener</button><button class="btn secondary" onclick="togglePresentation()">${S.presentation?'Salir de proyección':'Proyectar'}</button></div></div>`}
function createForm(){return `<div class="card"><h2>Guardar nueva pregunta</h2><div class="field"><label>Materia</label><input id="bs"></div><div class="field"><label>Tema</label><input id="bt"></div><div class="field"><label>Pregunta</label><input id="bp"></div>${[0,1,2,3].map(i=>`<div class="field"><label><input type="radio" name="bc" value="${i}"> Correcta ${String.fromCharCode(65+i)}</label><input id="bo${i}" placeholder="Opción ${String.fromCharCode(65+i)}"></div>`).join('')}<button class="btn primary" onclick="saveBank()">Guardar en banco</button><button class="btn ghost" onclick="showBank()">Cancelar</button></div>`}
function bankView(){return `<div class="card"><div style="display:flex;justify-content:space-between;align-items:center"><div><h2>Banco de preguntas</h2><p>Prepara tus reactivos y lánzalos en clase.</p></div><button class="btn primary" onclick="showCreate()">+ Guardar pregunta</button></div>${S.bank.length?S.bank.map(q=>`<div style="border-top:1px solid #e5e7eb;padding:16px 0"><small>${q.subject||'Sin materia'} · ${q.topic||'Sin tema'}</small><h3>${q.prompt}</h3><button class="btn primary" onclick="launchBank('${q.id}')">▶ Lanzar ahora</button> <button class="btn ghost" onclick="deleteBank('${q.id}')">Eliminar</button></div>`).join(''):'<p>Aún no tienes preguntas guardadas.</p>'}</div>`}
async function teacher(){if(!S.session){app.innerHTML=`<div class="join-wrap"><div class="join-card">${logo(true)}<p style="text-align:center;margin:0 0 22px;color:#6B7280">Interacción educativa en tiempo real</p><button class="btn primary" style="width:100%" onclick="createSession()">Crear sesión en vivo</button><button class="btn secondary" style="width:100%;margin-top:12px" onclick="go('join')">Entrar como alumno</button></div></div>`;return}const {count}=await sb.from('participants').select('*',{count:'exact',head:true}).eq('session_id',S.session.id),counts=(S.question?.options||[]).map((_,i)=>S.responses.filter(r=>r.answer===String(i)).length);let body;if(S.view==='bank')body=bankView();else if(S.view==='create')body=createForm();else body=`<section class="grid split"><div><div class="card"><span class="badge">${S.question?.status||'lista'}</span><h2>${S.question?.prompt||'Selecciona una pregunta de tu banco'}</h2>${S.question?(S.question.options||[]).map((o,i)=>`<div class="result-row"><div class="result-head"><span>${String.fromCharCode(65+i)}. ${o}${S.question.status==='revealed'&&String(i)===S.question.correct_answer?' ✓':''}</span><b>${counts[i]||0}</b></div><div class="bar"><i style="width:${S.responses.length?(counts[i]||0)/S.responses.length*100:0}%"></i></div></div>`).join(''):'<button class="btn primary" onclick="showBank()">Abrir banco de preguntas</button>'}${S.question?`<div style="display:flex;gap:10px;margin-top:20px"><button class="btn secondary" onclick="closeQuestion()">Cerrar respuestas</button><button class="btn primary" onclick="revealAnswer()">Mostrar respuesta</button></div>`:''}</div>${timerPanel()}${soundPanel()}</div><div class="card session-panel"><h3>Únete a la sesión</h3><div class="code">${S.session.code}</div><div id="joinQR" style="background:white;padding:12px;border-radius:14px;display:inline-block;margin:12px auto"></div><p>Escanea este QR con la cámara del celular o ingresa el código.</p><strong>${count||0} estudiantes conectados</strong></div></section>`;app.innerHTML=`<div class="shell"><header class="topbar">${logo()}<div class="topbar-actions"><button class="btn secondary" onclick="showLive()">En vivo</button><button class="btn secondary" onclick="showBank()">Banco de preguntas</button><button class="btn secondary" onclick="togglePresentation()">${S.presentation?'Salir proyección':'Proyectar'}</button><button class="btn secondary" onclick="endSession()">Finalizar</button></div></header><main class="content"><section class="hero"><div><h1>${S.session.title}</h1><p>${count||0} conectados · Código ${S.session.code}</p></div><button class="btn primary" onclick="showBank()">Banco de preguntas</button></section>${body}</main></div>`;setTimeout(drawQR,50)}
function join(){const preset=new URLSearchParams(location.hash.split('?')[1]||'').get('code')||'';app.innerHTML=`<div class="join-wrap"><div class="join-card">${logo(true)}<h2 style="text-align:center">Únete a la sesión</h2><p>Escanea el QR proyectado por tu profesor o ingresa el código.</p><div class="field"><label>Código</label><input id="code" maxlength="6" inputmode="numeric" value="${preset}"></div><div class="field"><label>Nombre</label><input id="name" placeholder="Tu nombre"></div><button class="btn primary" style="width:100%" onclick="joinSession()">Entrar</button></div></div>`}
function student(){if(!S.question){app.innerHTML=`<div class="join-wrap"><div class="join-card">${logo(true)}<h2 style="text-align:center">¡Estás dentro!</h2><p style="text-align:center">Espera la siguiente pregunta.</p></div></div>`;return}if(S.question.status!=='live'){const i=S.question.correct_answer;app.innerHTML=`<div class="join-wrap"><div class="join-card">${logo(true)}<h2 style="text-align:center">${S.question.status==='revealed'?'Resultado':'Respuestas cerradas'}</h2>${S.question.status==='revealed'&&i!=null?`<h3>✓ ${String.fromCharCode(65+Number(i))}. ${S.question.options[Number(i)]}</h3>`:'<p>Espera al profesor.</p>'}</div></div>`;return}app.innerHTML=`<div class="mobile-question"><div class="mobile-head">${logo()}<span class="badge live">Conectado</span></div><div class="mobile-body"><h1>${S.question.prompt}</h1>${S.question.options.map((o,i)=>`<button class="mobile-option" onclick="sendAnswer(${i})"><b>${String.fromCharCode(65+i)}</b> &nbsp; ${o}</button>`).join('')}</div></div>`}
async function render(){const r=(location.hash||'#teacher').slice(1).split('?')[0];if(r==='join')join();else if(r==='student')student();else await teacher()}
window.addEventListener('hashchange',render);render();