import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const c=window.TEDVIO_CONFIG||{},sb=createClient(c.SUPABASE_URL,c.SUPABASE_PUBLISHABLE_KEY),app=document.querySelector('#app');
const S={session:null,participant:null,question:null,responses:[],channel:null,editor:false};const logo=()=>`<div class="logo-fallback">TEDVIO</div>`,code=()=>String(Math.floor(100000+Math.random()*900000));
function go(r){location.hash=r;render()}window.go=go;
async function createSession(){let data,error;for(let i=0;i<5;i++){({data,error}=await sb.from('sessions').insert({code:code(),title:'Mi clase TEDVIO',status:'draft'}).select().single());if(!error)break}if(error)return alert(error.message);S.session=data;subscribe();render()}window.createSession=createSession;
async function joinSession(){const x=document.querySelector('#code').value.trim(),n=document.querySelector('#name').value.trim();if(!n)return alert('Escribe tu nombre');const {data:s}=await sb.from('sessions').select('*').eq('code',x).neq('status','closed').maybeSingle();if(!s)return alert('Código no válido');const {data:p,error}=await sb.from('participants').insert({session_id:s.id,display_name:n}).select().single();if(error)return alert(error.message);S.session=s;S.participant=p;subscribe();await refresh();go('student')}window.joinSession=joinSession;
function openEditor(){S.editor=true;render()}window.openEditor=openEditor;function closeEditor(){S.editor=false;render()}window.closeEditor=closeEditor;
async function publishQuestion(){const prompt=document.querySelector('#qp').value.trim(),opts=[0,1,2,3].map(i=>document.querySelector('#qo'+i).value.trim()),correct=document.querySelector('input[name=correct]:checked')?.value;if(!prompt||opts.some(x=>!x))return alert('Completa la pregunta y las cuatro opciones');const {data:last}=await sb.from('questions').select('position').eq('session_id',S.session.id).order('position',{ascending:false}).limit(1);const pos=(last?.[0]?.position||0)+1;const {data:q,error}=await sb.from('questions').insert({session_id:S.session.id,position:pos,prompt,question_type:'multiple_choice',options:opts,correct_answer:correct??null,status:'live',launched_at:new Date().toISOString()}).select().single();if(error)return alert(error.message);await sb.from('sessions').update({current_question_id:q.id,status:'live',started_at:new Date().toISOString()}).eq('id',S.session.id);S.question=q;S.responses=[];S.editor=false;await refresh()}window.publishQuestion=publishQuestion;
async function closeQuestion(){if(!S.question)return;await sb.from('questions').update({status:'closed',closed_at:new Date().toISOString()}).eq('id',S.question.id);await refresh()}window.closeQuestion=closeQuestion;
async function revealAnswer(){if(!S.question)return;await sb.from('questions').update({status:'revealed'}).eq('id',S.question.id);await refresh()}window.revealAnswer=revealAnswer;
async function endSession(){if(!confirm('¿Finalizar la sesión?'))return;await sb.from('sessions').update({status:'closed',closed_at:new Date().toISOString()}).eq('id',S.session.id);S.session=null;S.question=null;render()}window.endSession=endSession;
async function sendAnswer(i){if(!S.participant||!S.question||S.question.status!=='live')return;const {error}=await sb.from('responses').insert({question_id:S.question.id,participant_id:S.participant.id,answer:String(i)});if(error&&error.code!=='23505')return alert(error.message);document.querySelector('.mobile-body').innerHTML='<div style="text-align:center;padding-top:70px"><div style="font-size:64px">✓</div><h1>¡Respuesta enviada!</h1><p>Espera los resultados.</p></div>'}window.sendAnswer=sendAnswer;
async function refresh(){if(!S.session)return;const {data:s}=await sb.from('sessions').select('*').eq('id',S.session.id).single();S.session=s||S.session;if(S.session.current_question_id){const {data:q}=await sb.from('questions').select('*').eq('id',S.session.current_question_id).maybeSingle();S.question=q;const {data:r}=await sb.from('responses').select('*').eq('question_id',S.session.current_question_id);S.responses=r||[]}render()}
function subscribe(){if(S.channel)sb.removeChannel(S.channel);S.channel=sb.channel('tedvio-'+S.session.id).on('postgres_changes',{event:'*',schema:'public',table:'sessions',filter:`id=eq.${S.session.id}`},refresh).on('postgres_changes',{event:'*',schema:'public',table:'participants',filter:`session_id=eq.${S.session.id}`},refresh).on('postgres_changes',{event:'*',schema:'public',table:'questions',filter:`session_id=eq.${S.session.id}`},refresh).on('postgres_changes',{event:'*',schema:'public',table:'responses'},refresh).subscribe()}
function editor(){return `<div class="card"><div style="display:flex;justify-content:space-between"><h2>Nueva pregunta</h2><button class="btn ghost" onclick="closeEditor()">✕</button></div><div class="field"><label>Pregunta</label><input id="qp" placeholder="Escribe la pregunta"></div>${[0,1,2,3].map(i=>`<div class="field"><label><input type="radio" name="correct" value="${i}"> Respuesta correcta ${String.fromCharCode(65+i)}</label><input id="qo${i}" placeholder="Opción ${String.fromCharCode(65+i)}"></div>`).join('')}<button class="btn primary" onclick="publishQuestion()">Lanzar pregunta</button></div>`}
async function teacher(){if(!S.session){app.innerHTML=`<div class="join-wrap"><div class="join-card">${logo()}<h1>TEDVIO</h1><p>Interacción educativa en tiempo real</p><button class="btn primary" style="width:100%" onclick="createSession()">Crear sesión en vivo</button><button class="btn secondary" style="width:100%;margin-top:12px" onclick="go('join')">Entrar como alumno</button></div></div>`;return}const {count}=await sb.from('participants').select('*',{count:'exact',head:true}).eq('session_id',S.session.id),counts=(S.question?.options||[]).map((_,i)=>S.responses.filter(r=>r.answer===String(i)).length);app.innerHTML=`<div class="shell"><header class="topbar">${logo()}<div class="topbar-actions"><span class="badge live"><i class="dot"></i> EN VIVO</span><button class="btn secondary" onclick="endSession()">Finalizar</button></div></header><main class="content"><section class="hero"><div><h1>${S.session.title}</h1><p>${count||0} estudiantes conectados · Código ${S.session.code}</p></div><button class="btn primary" onclick="openEditor()">+ Nueva pregunta</button></section>${S.editor?editor():`<section class="grid split"><div class="card"><span class="badge">${S.question?.status||'sin pregunta'}</span><h2>${S.question?.prompt||'Esperando una pregunta'}</h2>${S.question?(S.question.options||[]).map((o,i)=>`<div class="result-row"><div class="result-head"><span>${String.fromCharCode(65+i)}. ${o}${S.question.status==='revealed'&&String(i)===S.question.correct_answer?' ✓':''}</span><b>${counts[i]||0}</b></div><div class="bar"><i style="width:${S.responses.length?(counts[i]||0)/S.responses.length*100:0}%"></i></div></div>`).join(''):'<p>Crea la primera pregunta para comenzar.</p>'}${S.question?`<div style="display:flex;gap:10px;margin-top:20px"><button class="btn secondary" onclick="closeQuestion()">Cerrar respuestas</button><button class="btn primary" onclick="revealAnswer()">Mostrar respuesta</button></div>`:''}</div><div class="card session-panel"><h3>Únete a la sesión</h3><div class="code">${S.session.code}</div><p>Comparte este código con tus alumnos.</p><strong>${count||0} conectados</strong></div></section>`}</main></div>`}
function join(){app.innerHTML=`<div class="join-wrap"><div class="join-card">${logo()}<h2>Únete a la sesión</h2><div class="field"><label>Código</label><input id="code" maxlength="6"></div><div class="field"><label>Nombre</label><input id="name" placeholder="Tu nombre"></div><button class="btn primary" style="width:100%" onclick="joinSession()">Entrar</button></div></div>`}
function student(){if(!S.question){app.innerHTML=`<div class="join-wrap"><div class="join-card">${logo()}<h2>¡Estás dentro!</h2><p>Espera a que el profesor lance una pregunta.</p><div class="code">${S.session?.code||''}</div></div></div>`;return}if(S.question.status!=='live'){const ci=S.question.correct_answer;app.innerHTML=`<div class="join-wrap"><div class="join-card">${logo()}<h2>${S.question.status==='revealed'?'Resultado':'Respuestas cerradas'}</h2><p>${S.question.prompt}</p>${S.question.status==='revealed'&&ci!=null?`<h3>✓ ${String.fromCharCode(65+Number(ci))}. ${S.question.options[Number(ci)]}</h3>`:'<p>Espera al profesor.</p>'}</div></div>`;return}app.innerHTML=`<div class="mobile-question"><div class="mobile-head">${logo()}<span class="badge live">Conectado</span></div><div class="mobile-body"><h1>${S.question.prompt}</h1>${(S.question.options||[]).map((o,i)=>`<button class="mobile-option" onclick="sendAnswer(${i})"><b>${String.fromCharCode(65+i)}</b> &nbsp; ${o}</button>`).join('')}</div></div>`}
async function render(){const r=(location.hash||'#teacher').slice(1);if(r==='join')join();else if(r==='student')student();else await teacher()}window.addEventListener('hashchange',render);render();