import {createClient} from 'https://esm.sh/@supabase/supabase-js@2';
const cfg=window.TEDVIO_CONFIG||{},db=createClient(cfg.SUPABASE_URL,cfg.SUPABASE_PUBLISHABLE_KEY);
const VERSION='2026.08.26.66',root=document.querySelector('#assignmentApp');
const S={code:(new URLSearchParams(location.search).get('code')||'').trim().toUpperCase(),meta:null,token:null,state:null,index:0,ordering:new Map(),hotspots:new Map(),timer:null,busy:false,identity:null};
const esc=(v='')=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const fmt=v=>v?new Date(v).toLocaleString('es-MX',{dateStyle:'medium',timeStyle:'short'}):'—';
const types={multiple_choice:'Opción múltiple',multiple_select:'Selección múltiple',true_false:'Verdadero / Falso',open_text:'Respuesta abierta',numeric:'Numérica',poll:'Encuesta',scale_5:'Escala 1–5',ordering:'Ordenar pasos',hotspot:'Hotspot'};
const key=code=>`tedvio.assignment.v66.${code}`;
const identityKey=code=>`tedvio.assignment.identity.v66.${code}`;
function logo(){return'<img class="as66-logo" src="./assets/tedvio_official_horizontal.svg?v=53" alt="TEDVIO">'}
function toast(msg){let n=document.querySelector('#as66Toast');if(!n){n=document.createElement('div');n.id='as66Toast';n.className='as66-toast';document.body.appendChild(n)}n.textContent=msg;n.classList.add('show');setTimeout(()=>n.classList.remove('show'),2200)}
function setOnline(){document.documentElement.dataset.online=navigator.onLine?'1':'0';const n=document.querySelector('#as66Net');if(n)n.textContent=navigator.onLine?'En línea':'Sin conexión'}
function errorText(e){const m=e?.message||String(e);if(m.includes('ASSIGNMENT_NOT_OPEN'))return'La actividad todavía no está abierta.';if(m.includes('ASSIGNMENT_CLOSED'))return'La actividad ya cerró.';if(m.includes('ASSIGNMENT_UNAVAILABLE'))return'La actividad no está disponible.';if(m.includes('ATTEMPTS_EXHAUSTED'))return'Ya utilizaste todos los intentos permitidos.';if(m.includes('STUDENT_NOT_IN_GROUP'))return'La matrícula no pertenece al grupo asignado.';if(m.includes('ENROLLMENT_REQUIRED'))return'Escribe tu matrícula.';return m}
async function meta(){if(!S.code)return entry();const{data,error}=await db.rpc('v2_public_assignment_meta',{p_code:S.code});if(error)return fail(errorText(error));S.meta=data;if(!data)return fail('Código de actividad no encontrado.');history.replaceState(null,'',`?code=${encodeURIComponent(S.code)}`);restore();if(S.token)return refreshState();renderLanding()}
function restore(){try{S.token=localStorage.getItem(key(S.code))||null;S.identity=JSON.parse(localStorage.getItem(identityKey(S.code))||'null')}catch{S.token=null;S.identity=null}}
function entry(){root.innerHTML=`<main class="as66-entry"><section class="as66-card entry">${logo()}<span class="as66-kicker">TEDVIO ASSIGNMENTS</span><h1>Resolver actividad</h1><p>Escribe el código compartido por tu profesor.</p><label>Código<input id="as66Code" maxlength="8" autocomplete="off" autocapitalize="characters" value="${esc(S.code)}"></label><button class="as66-primary" id="as66Go">Continuar</button></section></main>`;document.querySelector('#as66Go').onclick=()=>{S.code=document.querySelector('#as66Code').value.trim().toUpperCase();meta()}}
function fail(msg){root.innerHTML=`<main class="as66-entry"><section class="as66-card entry">${logo()}<span class="as66-kicker">TEDVIO ASSIGNMENTS</span><h1>No pudimos abrir la actividad</h1><p>${esc(msg)}</p><button class="as66-primary" onclick="location.href='./assignment.html'">Cambiar código</button></section></main>`}
function renderLanding(){if(!S.meta)return;const m=S.meta;if(S.token)return;const status=m.status;if(status==='scheduled'){root.innerHTML=`<main class="as66-entry"><section class="as66-card entry">${logo()}<span class="as66-chip scheduled">Programada</span><h1>${esc(m.title)}</h1><p>${esc(m.instructions||'')}</p><div class="as66-meta"><span><b>Abre</b>${fmt(m.opens_at)}</span><span><b>Cierra</b>${fmt(m.closes_at)}</span></div><button class="as66-secondary" onclick="location.reload()">Actualizar</button></section></main>`;return}if(status==='closed'){root.innerHTML=`<main class="as66-entry"><section class="as66-card entry">${logo()}<span class="as66-chip closed">Cerrada</span><h1>${esc(m.title)}</h1><p>Esta actividad ya no acepta nuevos intentos.</p>${S.identity?'<button class="as66-secondary" id="as66TryFeedback">Ver mi entrega</button>':''}</section></main>`;document.querySelector('#as66TryFeedback')?.addEventListener('click',()=>{restore();S.token&&refreshState()});return}root.innerHTML=`<main class="as66-entry"><section class="as66-card entry">${logo()}<span class="as66-chip open">Disponible</span><h1>${esc(m.title)}</h1><p>${esc(m.instructions||'')}</p><div class="as66-meta"><span><b>Grupo</b>${esc(m.group_name||'Actividad abierta')}</span><span><b>Intentos</b>${m.max_attempts}</span><span><b>Tiempo</b>${m.time_limit_minutes?m.time_limit_minutes+' min':'Sin límite'}</span><span><b>Cierre</b>${fmt(m.closes_at)}</span></div><div class="as66-join"><label>Matrícula<input id="as66Enrollment" autocomplete="off" value="${esc(S.identity?.enrollment||'')}"></label>${m.roster_required?'':`<label>Nombre completo<input id="as66Name" autocomplete="name" value="${esc(S.identity?.name||'')}"></label>`}<button class="as66-primary" id="as66Start">${S.identity?'Continuar / nuevo intento':'Comenzar'}</button></div></section></main>`;document.querySelector('#as66Start').onclick=startAttempt}
async function startAttempt(){if(S.busy)return;const enrollment=document.querySelector('#as66Enrollment')?.value.trim()||'',name=document.querySelector('#as66Name')?.value.trim()||S.identity?.name||'';if(!enrollment)return toast('Escribe tu matrícula.');S.busy=true;try{const{data,error}=await db.rpc('v2_assignment_start_attempt',{p_code:S.code,p_name:name,p_enrollment:enrollment});if(error)throw error;S.token=data?.token;if(!S.token)throw new Error('No se pudo crear el intento.');S.identity={enrollment,name:data?.display_name||name};localStorage.setItem(key(S.code),S.token);localStorage.setItem(identityKey(S.code),JSON.stringify(S.identity));await refreshState()}catch(e){toast(errorText(e))}finally{S.busy=false}}
async function refreshState(){if(!S.token)return renderLanding();const{data,error}=await db.rpc('v2_assignment_attempt_state',{p_token:S.token});if(error){toast(errorText(error));return}if(!data){localStorage.removeItem(key(S.code));S.token=null;return renderLanding()}S.state=data;const items=data.items||[];if(S.index>=items.length)S.index=Math.max(0,items.length-1);if(data.attempt?.status==='submitted')return renderFeedback();renderAttempt()}
function header(){const a=S.state?.assignment,at=S.state?.attempt;return`<header class="as66-top">${logo()}<div class="as66-top-right"><span id="as66Net">${navigator.onLine?'En línea':'Sin conexión'}</span><b>${esc(a?.code||S.code)}</b></div></header><div class="as66-context"><div><span>ACTIVIDAD</span><b>${esc(a?.title||'')}</b></div><div><span>ALUMNO</span><b>${esc(at?.display_name||'')}</b></div><div><span>INTENTO</span><b>${at?.attempt_no||1}</b></div><div><span>TIEMPO</span><b id="as66Timer">${timeText()}</b></div></div>`}
function timeLeft(){const exp=S.state?.attempt?.expires_at;if(!exp)return null;return Math.max(0,Math.ceil((new Date(exp).getTime()-Date.now())/1000))}
function timeText(){const s=timeLeft();if(s===null)return'Sin límite';const m=Math.floor(s/60),r=s%60;return`${m}:${String(r).padStart(2,'0')}`}
function startTimer(){clearInterval(S.timer);if(!S.state?.attempt?.expires_at)return;S.timer=setInterval(()=>{const el=document.querySelector('#as66Timer');if(el)el.textContent=timeText();if(timeLeft()===0){clearInterval(S.timer);setTimeout(()=>refreshState(),400)}},1000)}
function answered(){return Object.keys(S.state?.answers||{}).length}
function renderAttempt(){const items=S.state?.items||[],q=items[S.index];if(!q)return fail('La actividad no contiene preguntas.');root.innerHTML=`<main class="as66-app">${header()}<section class="as66-progress"><div><b>${answered()} de ${items.length}</b><span>respondidas</span></div><div class="as66-track"><i style="width:${items.length?answered()/items.length*100:0}%"></i></div><button class="as66-submit" onclick="as66SubmitAttempt()">Entregar actividad</button></section><section class="as66-stage"><aside class="as66-nav">${items.map((x,i)=>`<button class="${i===S.index?'active':''} ${S.state.answers?.[x.id]!==undefined?'done':''}" onclick="as66Goto(${i})">${i+1}</button>`).join('')}</aside><article class="as66-question"><div class="as66-qmeta"><span>Pregunta ${S.index+1} de ${items.length}</span><span>${esc(types[q.question_type]||q.question_type)}</span><span>${Number(q.points||0)} pt${Number(q.points||0)===1?'':'s'}</span></div><h1>${esc(q.prompt)}</h1>${media(q)}<div id="as66Answer">${answerUi(q)}</div><div class="as66-qactions"><button class="as66-secondary" onclick="as66Goto(${Math.max(0,S.index-1)})" ${S.index===0?'disabled':''}>← Anterior</button><button class="as66-secondary" onclick="as66Goto(${Math.min(items.length-1,S.index+1)})" ${S.index===items.length-1?'disabled':''}>Siguiente →</button></div></article></section></main>`;bindAnswer(q);startTimer();setOnline()}
function media(q){if(!q.media_url)return'';if(q.media_type==='image')return`<img class="as66-media" src="${esc(q.media_url)}" alt="Recurso de la pregunta">`;if(q.media_type==='audio')return`<audio class="as66-audio" controls src="${esc(q.media_url)}"></audio>`;if(q.media_type==='video')return`<video class="as66-media" controls src="${esc(q.media_url)}"></video>`;return''}
function answerUi(q){const cur=S.state.answers?.[q.id],opts=Array.isArray(q.options)?q.options:[];if(['multiple_choice','true_false','poll'].includes(q.question_type))return`<div class="as66-options">${opts.map(o=>`<button class="${same(cur,o)?'selected':''}" data-one="${esc(o)}">${esc(o)}</button>`).join('')}</div>${saved(cur)}`;if(q.question_type==='multiple_select')return`<div class="as66-options checks">${opts.map(o=>`<label><input class="as66-multi" type="checkbox" value="${esc(o)}" ${Array.isArray(cur)&&cur.includes(o)?'checked':''}><span>${esc(o)}</span></label>`).join('')}</div><button class="as66-primary compact" id="as66SaveMulti">Guardar respuesta</button>${saved(cur)}`;if(q.question_type==='scale_5')return`<div class="as66-scale">${['1','2','3','4','5'].map(x=>`<button class="${String(cur)===x?'selected':''}" data-scale="${x}">${x}</button>`).join('')}</div>${saved(cur)}`;if(q.question_type==='open_text')return`<textarea id="as66Open" rows="7" placeholder="Escribe tu respuesta…">${esc(cur??'')}</textarea><button class="as66-primary compact" id="as66SaveOpen">Guardar respuesta</button>${saved(cur)}`;if(q.question_type==='numeric')return`<input id="as66Num" class="as66-number" type="number" step="any" value="${cur??''}" placeholder="Respuesta numérica"><button class="as66-primary compact" id="as66SaveNum">Guardar respuesta</button>${saved(cur)}`;if(q.question_type==='ordering')return orderingUi(q,cur,opts);if(q.question_type==='hotspot')return hotspotUi(q,cur);return'<p>Tipo de pregunta no disponible.</p>'}
function saved(v){return v===undefined?'':'<div class="as66-saved">✓ Respuesta guardada</div>'}
function same(a,b){return JSON.stringify(a)===JSON.stringify(b)}
function orderingUi(q,cur,opts){let order=S.ordering.get(q.id);if(!order){order=Array.isArray(cur)?[...cur]:[];S.ordering.set(q.id,order)}const remaining=opts.filter(x=>!order.includes(x));return`<div class="as66-order"><div class="as66-order-selected">${order.length?order.map((x,i)=>`<div><span>${i+1}</span><b>${esc(x)}</b><button data-order-remove="${i}">×</button></div>`).join(''):'<p>Toca los elementos en el orden correcto.</p>'}</div><div class="as66-order-choices">${remaining.map(x=>`<button data-order-add="${esc(x)}">${esc(x)}</button>`).join('')}</div><div class="as66-inline"><button class="as66-secondary" id="as66OrderReset">Reiniciar</button><button class="as66-primary compact" id="as66OrderSave" ${order.length!==opts.length?'disabled':''}>Guardar orden</button></div>${saved(cur)}</div>`}
function hotspotUi(q,cur){const p=S.hotspots.get(q.id)||((cur&&typeof cur==='object')?cur:null);if(p&&!S.hotspots.has(q.id))S.hotspots.set(q.id,p);return`<div class="as66-hotspot"><div class="as66-hotspot-img" id="as66HotspotImg"><img src="${esc(q.media_url||'')}" alt="Selecciona una zona">${p?`<i style="left:${Number(p.x)}%;top:${Number(p.y)}%"></i>`:''}</div><p>${p?`Punto seleccionado: ${Number(p.x).toFixed(1)}%, ${Number(p.y).toFixed(1)}%`:'Toca la zona que consideres correcta.'}</p><button class="as66-primary compact" id="as66HotspotSave" ${p?'':'disabled'}>Guardar punto</button>${saved(cur)}</div>`}
function bindAnswer(q){if(['multiple_choice','true_false','poll'].includes(q.question_type))document.querySelectorAll('[data-one]').forEach(b=>b.onclick=()=>saveAnswer(q,b.dataset.one));if(q.question_type==='scale_5')document.querySelectorAll('[data-scale]').forEach(b=>b.onclick=()=>saveAnswer(q,b.dataset.scale));if(q.question_type==='multiple_select')document.querySelector('#as66SaveMulti').onclick=()=>{const a=[...document.querySelectorAll('.as66-multi:checked')].map(x=>x.value).sort();if(!a.length)return toast('Selecciona al menos una opción.');saveAnswer(q,a)};if(q.question_type==='open_text')document.querySelector('#as66SaveOpen').onclick=()=>{const a=document.querySelector('#as66Open').value.trim();if(!a)return toast('Escribe una respuesta.');saveAnswer(q,a)};if(q.question_type==='numeric')document.querySelector('#as66SaveNum').onclick=()=>{const v=document.querySelector('#as66Num').value;if(v==='')return toast('Escribe un número.');saveAnswer(q,Number(v))};if(q.question_type==='ordering')bindOrdering(q);if(q.question_type==='hotspot')bindHotspot(q)}
function bindOrdering(q){document.querySelectorAll('[data-order-add]').forEach(b=>b.onclick=()=>{const a=S.ordering.get(q.id)||[];if(!a.includes(b.dataset.orderAdd))a.push(b.dataset.orderAdd);S.ordering.set(q.id,a);renderAttempt()});document.querySelectorAll('[data-order-remove]').forEach(b=>b.onclick=()=>{const a=S.ordering.get(q.id)||[];a.splice(Number(b.dataset.orderRemove),1);S.ordering.set(q.id,a);renderAttempt()});document.querySelector('#as66OrderReset').onclick=()=>{S.ordering.set(q.id,[]);renderAttempt()};document.querySelector('#as66OrderSave').onclick=()=>saveAnswer(q,[...(S.ordering.get(q.id)||[])])}
function bindHotspot(q){const box=document.querySelector('#as66HotspotImg');if(!box)return;box.onclick=e=>{const r=box.getBoundingClientRect(),p={x:Math.max(0,Math.min(100,(e.clientX-r.left)/r.width*100)),y:Math.max(0,Math.min(100,(e.clientY-r.top)/r.height*100))};S.hotspots.set(q.id,p);renderAttempt()};document.querySelector('#as66HotspotSave').onclick=()=>saveAnswer(q,S.hotspots.get(q.id))}
async function saveAnswer(q,answer){if(!navigator.onLine)return toast('Sin conexión. Recupera internet para guardar.');if(S.busy)return;S.busy=true;try{const{data,error}=await db.rpc('v2_assignment_submit_answer',{p_token:S.token,p_item_id:q.id,p_answer:answer});if(error)throw error;if(data?.expired||data?.submitted){await refreshState();return}S.state.answers=S.state.answers||{};S.state.answers[q.id]=answer;toast('Respuesta guardada.');renderAttempt()}catch(e){toast(errorText(e))}finally{S.busy=false}}
function goto(i){S.index=Math.max(0,Math.min((S.state?.items?.length||1)-1,Number(i)||0));renderAttempt();window.scrollTo({top:0,behavior:'smooth'})}
async function submitAttempt(){if(S.busy)return;const total=S.state?.items?.length||0,done=answered();if(!confirm(done<total?`Has respondido ${done} de ${total}. ¿Entregar de todos modos?`:'¿Entregar la actividad? Después ya no podrás cambiar respuestas.'))return;S.busy=true;try{const{data,error}=await db.rpc('v2_assignment_submit_attempt',{p_token:S.token});if(error)throw error;if(data?.submitted){S.state.attempt.status='submitted';S.state.attempt.submitted_at=data.submitted_at||new Date().toISOString();await renderFeedback(data)}else await refreshState()}catch(e){toast(errorText(e))}finally{S.busy=false}}
async function renderFeedback(prefetched=null){clearInterval(S.timer);let f=prefetched;if(!f){const{data,error}=await db.rpc('v2_assignment_feedback',{p_token:S.token});if(error)return toast(errorText(error));f=data}const a=S.state?.assignment||S.meta||{},at=S.state?.attempt||{},items=S.state?.items||[],imap=new Map(items.map(x=>[x.id,x]));if(!f?.submitted)return refreshState();root.innerHTML=`<main class="as66-entry"><section class="as66-card result">${logo()}<span class="as66-chip open">Entrega recibida</span><h1>${esc(a.title||S.meta?.title||'Actividad')}</h1><p>${f.auto_submitted?'El tiempo terminó y TEDVIO entregó tu intento automáticamente.':'Tu intento fue entregado correctamente.'}${f.late?' Se registró como entrega tardía.':''}</p>${f.released?`<div class="as66-score"><b>${f.percentage===null?'—':Math.round(Number(f.percentage))+'%'}</b><span>${f.score??'—'} / ${f.max_score??'—'} puntos</span></div>`:`<div class="as66-wait-result"><b>Resultados pendientes</b><span>${f.release_at?'Se publicarán después de '+fmt(f.release_at)+'.':'El profesor publicará los resultados al cerrar la actividad.'}</span></div>`}${f.show_answers?`<div class="as66-feedback-list">${(f.details||[]).map((d,i)=>{const q=imap.get(d.item_id);return`<article><div><span>${i+1}</span><b>${esc(q?.prompt||'Pregunta')}</b></div><p>Tu respuesta: <strong>${esc(answerText(d.answer))}</strong></p><p>Respuesta correcta: <strong>${esc(answerText(d.correct_answer))}</strong></p><span class="${d.is_correct===true?'ok':d.is_correct===false?'bad':'neutral'}">${d.is_correct===true?'✓ Correcta':d.is_correct===false?'× Incorrecta':'Sin calificación automática'}</span>${d.explanation?`<div class="as66-explain"><b>Explicación</b>${esc(d.explanation)}</div>`:''}</article>`}).join('')}</div>`:''}<div class="as66-result-actions"><button class="as66-secondary" onclick="as66RefreshFeedback()">Actualizar resultados</button>${S.meta?.status==='open'?'<button class="as66-primary" onclick="as66NewAttempt()">Intentar de nuevo</button>':''}</div></section></main>`;setOnline()}
function answerText(v){if(v===null||v===undefined)return'—';if(Array.isArray(v))return v.join(' → ');if(typeof v==='object')return v.x!==undefined?`Punto ${Number(v.x).toFixed(1)}%, ${Number(v.y).toFixed(1)}%`:JSON.stringify(v);return String(v)}
async function refreshFeedback(){await meta()}
async function newAttempt(){if(!S.identity)return renderLanding();localStorage.removeItem(key(S.code));S.token=null;S.state=null;S.index=0;S.ordering.clear();S.hotspots.clear();renderLanding()}
window.as66Goto=goto;window.as66SubmitAttempt=submitAttempt;window.as66RefreshFeedback=refreshFeedback;window.as66NewAttempt=newAttempt;
window.addEventListener('online',()=>{setOnline();S.token&&refreshState()});window.addEventListener('offline',setOnline);document.addEventListener('visibilitychange',()=>{if(!document.hidden&&S.token)refreshState()});
setOnline();meta();
