import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const cfg=window.TEDVIO_CONFIG||{},sb=createClient(cfg.SUPABASE_URL,cfg.SUPABASE_PUBLISHABLE_KEY);
const esc=(v='')=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
let userCache=null;
async function me(){if(userCache)return userCache;userCache=(await sb.auth.getUser()).data?.user||null;return userCache}
async function injectResume(){if(!document.querySelector('.b-hero h1')?.textContent.includes('Panel del profesor')||document.querySelector('#pmResume'))return;const u=await me();if(!u)return;const {data}=await sb.from('v2_sessions').select('*').eq('teacher_id',u.id).neq('status','closed').order('created_at',{ascending:false}).limit(1).maybeSingle();if(!data)return;const hero=document.querySelector('.b-hero'),box=document.createElement('div');box.id='pmResume';box.className='pm-resume';box.innerHTML=`<div><strong>▶ Sesión pendiente</strong><span>${esc(data.title)} · Código ${esc(data.code)}${data.group_name?' · '+esc(data.group_name):''}</span></div><button class="b-btn primary">Reanudar sesión</button>`;box.querySelector('button').onclick=()=>window.betaOpenSession?.(data.id);hero.parentElement.insertBefore(box,hero.nextSibling)}
function sessionCode(){const main=document.querySelector('#sessionMain');if(!main)return null;return [...main.querySelectorAll('.b-code')][0]?.textContent.trim()||main.textContent.match(/Código\s+(\d{6})/)?.[1]||null}
function injectSessionLinks(){const top=document.querySelector('.b-top-actions'),code=sessionCode();if(!top||!code||document.querySelector('#pmProjectionLink'))return;const control=document.createElement('button');control.className='b-btn dark';control.textContent='📱 Control móvil';control.onclick=()=>window.open(`./control.html?code=${encodeURIComponent(code)}`,'_blank');const projection=document.createElement('button');projection.id='pmProjectionLink';projection.className='b-btn primary';projection.textContent='📽 Proyección';projection.onclick=()=>window.open(`./proyectar.html?code=${encodeURIComponent(code)}`,'_blank');top.prepend(projection);top.prepend(control)}
function injectPdfButton(){const report=document.querySelector('#reportContent');if(!report||document.querySelector('#pmPdfBtn'))return;const xlsx=[...report.querySelectorAll('button')].find(b=>b.textContent.trim()==='Excel'),onclick=xlsx?.getAttribute('onclick')||'',id=onclick.match(/betaExportReport\('([^']+)'/)?.[1];if(!id)return;const b=document.createElement('button');b.id='pmPdfBtn';b.className='b-btn primary';b.textContent='PDF institucional';b.onclick=()=>exportPdf(id);xlsx?.parentElement?.prepend(b)}
async function exportPdf(sessionId){if(!window.jspdf)return alert('El módulo PDF todavía está cargando.');const {jsPDF}=window.jspdf,[s,p,q]=await Promise.all([sb.from('v2_sessions').select('*').eq('id',sessionId).single(),sb.from('v2_participants').select('*').eq('session_id',sessionId),sb.from('v2_questions').select('*').eq('session_id',sessionId).order('position')]),sess=s.data,parts=p.data||[],qs=q.data||[],ids=qs.map(x=>x.id);let res=[];if(ids.length)res=(await sb.from('v2_responses').select('*').in('question_id',ids)).data||[];const doc=new jsPDF({unit:'mm',format:'a4'});doc.setTextColor(7,26,59);doc.setFontSize(20);doc.text('TEDVIO · Reporte de sesión',15,18);doc.setFontSize(11);doc.text(sess.university||'Universidad / institución',15,28);doc.text(sess.educational_program||'Programa educativo',15,34);doc.text(`Grupo: ${sess.group_name||'—'}   |   Sesión: ${sess.title}`,15,40);doc.text(`Participantes: ${parts.length}   |   Código: ${sess.code}`,15,46);const rows=parts.map(pp=>{const rr=res.filter(r=>r.participant_id===pp.id);return [pp.matricula||'',pp.display_name,String(rr.filter(r=>r.is_correct).length),String(rr.length),String(rr.reduce((a,r)=>a+(r.points||0),0))]});if(doc.autoTable)doc.autoTable({startY:54,head:[['Matrícula','Alumno','Correctas','Respondidas','Puntos']],body:rows,styles:{fontSize:9},headStyles:{fillColor:[7,26,59]}});else rows.slice(0,25).forEach((r,i)=>doc.text(r.join(' | '),15,56+i*6));let y=doc.lastAutoTable?.finalY?doc.lastAutoTable.finalY+10:210;const graded=qs.filter(x=>['multiple_choice','multiple_select','true_false','numeric','ordering','hotspot'].includes(x.question_type));if(y>250){doc.addPage();y=18}doc.setFontSize(14);doc.text('Resumen académico',15,y);y+=8;for(const x of graded.slice(0,10)){const rr=res.filter(r=>r.question_id===x.id),pct=rr.length?Math.round(rr.filter(r=>r.is_correct).length/rr.length*100):0;doc.setFontSize(9);doc.text(`P${x.position}. ${String(x.prompt).slice(0,85)} — ${pct}% acierto`,15,y);y+=6;if(y>280){doc.addPage();y=18}}doc.save(`TEDVIO-${sess.group_name||sess.code}.pdf`)}
function installPwa(){if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});let deferred;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e;const wait=setInterval(()=>{const top=document.querySelector('.b-top-actions');if(!top||document.querySelector('#pmInstall'))return;clearInterval(wait);const b=document.createElement('button');b.id='pmInstall';b.className='b-btn dark';b.textContent='⬇ Instalar';b.onclick=async()=>{deferred.prompt();await deferred.userChoice;b.remove()};top.appendChild(b)},400)})}
function injectAcademicLabels(){const hero=document.querySelector('#sessionMain .b-hero');if(!hero||document.querySelector('#pmSessionAcademic'))return;const code=sessionCode();if(!code)return;sb.rpc('v2_public_session_meta',{p_code:code}).then(({data})=>{const s=data?.[0];if(!s||!hero.isConnected)return;const p=hero.querySelector('p');if(!p)return;const line=document.createElement('div');line.id='pmSessionAcademic';line.style.marginTop='7px';line.innerHTML=`${s.university?`<span class="pm-academic-chip">🏫 ${esc(s.university)}</span>`:''}${s.educational_program?` <span class="pm-academic-chip">🎓 ${esc(s.educational_program)}</span>`:''}${s.group_name?` <span class="pm-academic-chip">👥 ${esc(s.group_name)}</span>`:''}`;p.after(line)})}
setInterval(()=>{try{injectResume();injectSessionLinks();injectPdfButton();injectAcademicLabels()}catch(e){console.error('TEDVIO UX',e)}},700);installPwa();
