import{createClient}from'https://esm.sh/@supabase/supabase-js@2';
const cfg=window.TEDVIO_CONFIG||{},db=createClient(cfg.SUPABASE_URL,cfg.SUPABASE_PUBLISHABLE_KEY),root=document.querySelector('#controlApp');
const VERSION='2026.08.25.59',graded=new Set(['multiple_choice','multiple_select','true_false','numeric','ordering','hotspot']);
const esc=(v='')=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const state={user:null,code:new URLSearchParams(location.search).get('code')||sessionStorage.getItem('tedvio.v59.code')||'',session:null,group:null,participants:[],questions:[],responses:[],question:null,poll:null,tick:null,pollBusy:false,actionBusy:false,renderKey:'',showRanking:sessionStorage.getItem('tedvio.v59.ranking')!=='0',allAnsweredKey:'',lastGoodAt:0,offline:!navigator.onLine};
const now=()=>new Date().toISOString();
function logo(){return'<img class="mc59-logo" src="./assets/tedvio_official_horizontal.svg?v=59" alt="TEDVIO">'}
function remaining(q=state.question){if(!q?.launched_at||q.status!=='live')return 0;return Math.max(0,Math.ceil(Number(q.timer_seconds||30)-(Date.now()-new Date(q.launched_at).getTime())/1000))}
function statusLabel(q=state.question){if(!q)return'Sala de espera';return q.status==='live'?'Aceptando respuestas':q.status==='closed'?'Respuestas cerradas':q.status==='revealed'?'Respuesta revelada':q.status}
function currentResponses(){return state.question?state.responses.filter(r=>r.question_id===state.question.id):[]}
function nextQueued(){if(!state.question)return state.questions.filter(q=>q.status==='queued').sort((a,b)=>a.position-b.position)[0]||null;return state.questions.filter(q=>q.status==='queued'&&Number(q.position)>Number(state.question.position)).sort((a,b)=>a.position-b.position)[0]||null}
function previousLaunched(){if(!state.question)return null;return state.questions.filter(q=>Number(q.position)<Number(state.question.position)&&q.status!=='queued').sort((a,b)=>b.position-a.position)[0]||null}
function participation(){const answered=currentResponses().length,total=state.participants.length;return{answered,total,pending:Math.max(0,total-answered),pct:total?Math.round(answered/total*100):0,all:total>0&&answered>=total}}
function scoreRows(){const rows=state.participants.map(p=>({id:p.id,name:p.display_name||'Alumno',team:p.team_name||'',pts:0,correct:0,answered:0,streak:0,last:''})),map=new Map(rows.map(x=>[x.id,x]));for(const r of state.responses){const x=map.get(r.participant_id);if(!x)continue;x.pts+=Number(r.points||0);x.answered++;if(r.is_correct)x.correct++;if(!x.last||new Date(r.submitted_at)>new Date(x.last)){x.last=r.submitted_at;x.streak=Number(r.streak||0)}}if(state.session?.team_mode){const tm=new Map();for(const r of rows){const k=r.team||'Sin equipo',x=tm.get(k)||{id:k,name:k,pts:0,correct:0,answered:0,streak:0};x.pts+=r.pts;x.correct+=r.correct;x.answered+=r.answered;tm.set(k,x)}return[...tm.values()].sort((a,b)=>b.pts-a.pts||b.correct-a.correct)}return rows.sort((a,b)=>b.pts-a.pts||b.correct-a.correct||a.name.localeCompare(b.name))}
async function boot(){const{data:{session}}=await db.auth.getSession();state.user=session?.user||null;if(!state.user)return renderLogin();if(!/^\d{6}$/.test(state.code))return renderCode();sessionStorage.setItem('tedvio.v59.code',state.code);await openSession();startLoops()}
function renderLogin(){stopLoops();root.innerHTML=`<div class="mc59-auth"><div class="mc59-auth-card">${logo()}<span class="mc59-kicker">Mobile Classroom Pro</span><h1>Control del profesor</h1><p>Maneja tu sesión TEDVIO desde el celular.</p><label>Correo<input id="mc59Email" type="email" autocomplete="email"></label><label>Contraseña<input id="mc59Pass" type="password" autocomplete="current-password"></label><button id="mc59Login" class="mc59-btn primary">Entrar</button></div></div>`;document.querySelector('#mc59Login').onclick=async()=>{const b=document.querySelector('#mc59Login');b.disabled=true;b.textContent='Entrando…';const{error}=await db.auth.signInWithPassword({email:document.querySelector('#mc59Email').value.trim(),password:document.querySelector('#mc59Pass').value});if(error){b.disabled=false;b.textContent='Entrar';return alert(error.message)}boot()}}
function renderCode(){stopLoops();root.innerHTML=`<div class="mc59-auth"><div class="mc59-auth-card">${logo()}<span class="mc59-kicker">Mobile Classroom Pro</span><h1>Abrir control</h1><p>Escribe el código de tu sesión activa.</p><label>Código de 6 dígitos<input id="mc59Code" inputmode="numeric" maxlength="6" autocomplete="one-time-code"></label><button id="mc59Open" class="mc59-btn primary">Abrir sesión</button><button id="mc59Teacher" class="mc59-btn secondary">Volver a TEDVIO</button></div></div>`;document.querySelector('#mc59Open').onclick=()=>{const c=document.querySelector('#mc59Code').value.trim();if(!/^\d{6}$/.test(c))return alert('Escribe un código de 6 dígitos.');state.code=c;sessionStorage.setItem('tedvio.v59.code',c);history.replaceState(null,'',`?code=${c}`);openSession().then(startLoops)};document.querySelector('#mc59Teacher').onclick=()=>location.href='/teacher'}
async function openSession(){if(!state.user)return;const{data,error}=await db.from('v2_sessions').select('*').eq('code',state.code).eq('teacher_id',state.user.id).maybeSingle();if(error)throw error;if(!data)return renderMissing();state.session=data;await refresh(true)}
function renderMissing(){stopLoops();root.innerHTML=`<div class="mc59-auth"><div class="mc59-auth-card">${logo()}<h1>Sesión no encontrada</h1><p>Verifica el código o la cuenta del profesor.</p><button id="mc59Retry" class="mc59-btn primary">Cambiar código</button></div></div>`;document.querySelector('#mc59Retry').onclick=()=>{state.code='';sessionStorage.removeItem('tedvio.v59.code');history.replaceState(null,'','./control.html');renderCode()}}
async function refresh(force=false){if(state.pollBusy||state.actionBusy||!state.session)return;state.pollBusy=true;try{const id=state.session.id,[s,p,q,g]=await Promise.all([db.from('v2_sessions').select('*').eq('id',id).eq('teacher_id',state.user.id).single(),db.from('v2_participants').select('id,display_name,team_name,matricula,joined_at').eq('session_id',id).order('joined_at'),db.from('v2_questions').select('*').eq('session_id',id).order('position'),state.session.group_id?db.from('v2_groups').select('id,name,group_name,subject,program,university,term,school_cycle').eq('id',state.session.group_id).maybeSingle():Promise.resolve({data:null})]);if(s.error)throw s.error;state.session=s.data||state.session;if(state.session.status==='closed'){paintClosed();return}state.participants=p.data||[];state.questions=q.data||[];state.group=g.data||null;state.question=state.questions.find(x=>x.id===state.session.current_question_id)||null;const ids=state.questions.map(x=>x.id);if(ids.length){const r=await db.from('v2_responses').select('question_id,participant_id,answer,is_correct,points,streak,submitted_at').in('question_id',ids);if(r.error)throw r.error;state.responses=r.data||[]}else state.responses=[];state.lastGoodAt=Date.now();state.offline=false;paint(force);notifyAllAnswered()}catch(e){console.error('TEDVIO Mobile Classroom v59',e);state.offline=true;paint(true)}finally{state.pollBusy=false}}
function key(){const p=participation();return`${state.session?.id}:${state.session?.status}:${state.question?.id||'room'}:${state.question?.status||''}:${state.participants.length}:${p.answered}:${state.responses.reduce((a,r)=>a+Number(r.points||0),0)}:${state.showRanking}:${state.offline}`}
function paint(force=false){if(!state.session||state.session.status==='closed')return;const k=key();if(!force&&k===state.renderKey){tickTimer();return}state.renderKey=k;root.innerHTML=state.question?liveHtml():roomHtml();tickTimer()}
function shellTop(){return`<header class="mc59-top">${logo()}<div><span class="mc59-live ${state.offline?'offline':''}">${state.offline?'Reconectando':'En línea'}</span><span class="mc59-code">${esc(state.code)}</span></div></header>`}
function roomHtml(){const queued=state.questions.filter(q=>q.status==='queued').sort((a,b)=>a.position-b.position),name=state.group?.name||state.group?.group_name||'',meta=[state.group?.subject,state.group?.program,state.group?.term||state.group?.school_cycle].filter(Boolean).join(' · ');return`<div class="mc59-app">${shellTop()}<section class="mc59-hero"><span class="mc59-kicker">Sala de espera${name?` · ${esc(name)}`:''}</span><h1>${esc(state.session.title||'Sesión TEDVIO')}</h1><p>${esc(meta||'La sesión está lista para comenzar.')}</p><div class="mc59-room-code"><span>Código</span><b>${esc(state.code)}</b><button class="mc59-btn ghost" onclick="mc59CopyCode()">Copiar</button></div></section><section class="mc59-grid room"><article class="mc59-card"><div class="mc59-title"><div><h2>Conectados</h2><p>Alumnos dentro de la sesión.</p></div><strong>${state.participants.length}</strong></div><div class="mc59-people">${state.participants.length?state.participants.map(p=>`<span><i></i>${esc(p.display_name)}</span>`).join(''):'<span><i></i>Esperando alumnos…</span>'}</div></article><article class="mc59-card"><div class="mc59-title"><div><h2>Preparación</h2><p>${queued.length} pregunta${queued.length===1?'':'s'} en cola.</p></div></div><div class="mc59-primary-stack">${queued.length?`<button class="mc59-btn primary XL" onclick="mc59Launch('${queued[0].id}')">▶ Iniciar primera pregunta</button>`:''}<button class="mc59-btn secondary" onclick="mc59Project()">▣ Abrir proyección</button><button class="mc59-btn secondary" onclick="mc59CopyCode()">Copiar código</button><button class="mc59-btn danger" onclick="mc59End()">Finalizar sesión</button></div></article></section></div>`}
function questionStrip(){return`<nav class="mc59-strip">${state.questions.map(q=>`<button class="${state.question?.id===q.id?'current':q.status==='queued'?'queued':'done'}" ${q.status==='queued'?'disabled':`onclick="mc59Show('${q.id}')"`}>${q.position}</button>`).join('')}</nav>`}
function liveHtml(){const q=state.question,p=participation(),next=nextQueued(),prev=previousLaunched(),rank=state.showRanking?rankingHtml():'';return`<div class="mc59-app">${shellTop()}${p.all?'<div class="mc59-all">Todos respondieron <b>✓</b></div>':''}${questionStrip()}<section class="mc59-question"><div class="mc59-qtop"><div><span class="mc59-chip ${q.status}">${esc(statusLabel(q))}</span><span class="mc59-chip">Pregunta ${q.position} de ${state.questions.length}</span></div><div class="mc59-timer" id="mc59Timer"><b id="mc59Time">${q.status==='live'?remaining(q)+'s':'—'}</b></div></div><h1>${esc(q.prompt)}</h1><div class="mc59-participation"><div><span>Conectados</span><b>${p.total}</b></div><div><span>Respondieron</span><b>${p.answered}</b></div><div><span>Pendientes</span><b>${p.pending}</b></div></div><div class="mc59-progress"><i style="width:${p.pct}%"></i></div><div class="mc59-answer-status">${state.participants.map(x=>`<span class="${currentResponses().some(r=>r.participant_id===x.id)?'answered':''}"><i></i>${esc(x.display_name)}</span>`).join('')||'<span>Sin alumnos conectados.</span>'}</div></section>${state.session.competitive?`<section class="mc59-card"><div class="mc59-title"><div><h2>${state.session.team_mode?'Ranking por equipos':'Ranking en vivo'}</h2><p>${state.showRanking?'Visible en tu control':'Oculto en tu control'}</p></div><button class="mc59-btn mini secondary" onclick="mc59ToggleRanking()">${state.showRanking?'Ocultar':'Mostrar'}</button></div>${rank}</section>`:''}<footer class="mc59-controls"><div class="mc59-flow">${q.status==='live'?`<button class="mc59-btn secondary XL" onclick="mc59Close()">Cerrar respuestas</button>`:''}${q.status!=='revealed'&&graded.has(q.question_type)?`<button class="mc59-btn success XL" onclick="mc59Reveal()">Mostrar respuesta</button>`:''}${next?`<button class="mc59-btn primary XL" onclick="mc59Next('${next.id}')">Siguiente ▶</button>`:`<button class="mc59-btn primary XL" disabled>Sin siguiente</button>`}</div><div class="mc59-more">${prev?`<button class="mc59-btn secondary" onclick="mc59Show('${prev.id}')">◀ Anterior</button>`:''}<button class="mc59-btn secondary" onclick="mc59Room()">Sala</button><button class="mc59-btn secondary" onclick="mc59Project()">Proyección</button><button class="mc59-btn secondary" onclick="mc59CopyCode()">Copiar código</button><button class="mc59-btn danger" onclick="mc59End()">Finalizar</button></div></footer></div>`}
function rankingHtml(){const rows=scoreRows();return`<div class="mc59-rank">${rows.slice(0,8).map((r,i)=>`<div><span>${i+1}</span><p><b>${esc(r.name)}</b><small>${r.correct} correctas${r.streak?` · 🔥 ${r.streak}`:''}</small></p><strong>${r.pts}</strong></div>`).join('')||'<p class="mc59-empty">Aún no hay puntuación.</p>'}</div>`}
function tickTimer(){const q=state.question,t=document.querySelector('#mc59Time'),ring=document.querySelector('#mc59Timer');if(!q||!t||!ring)return;const rem=remaining(q),max=Math.max(1,Number(q.timer_seconds||30)),pct=q.status==='live'?Math.max(0,Math.min(100,rem/max*100)):0;t.textContent=q.status==='live'?rem+'s':'—';ring.style.setProperty('--pct',pct+'%')}
function notifyAllAnswered(){const p=participation();if(!p.all||!state.question)return;const k=state.question.id+':'+p.answered;if(state.allAnsweredKey===k)return;state.allAnsweredKey=k;try{navigator.vibrate?.([25,35,25])}catch{} }
async function action(fn){if(state.actionBusy)return;state.actionBusy=true;try{await fn();state.renderKey='';await refresh(true)}catch(e){console.error(e);alert(e.message||'No se pudo completar la acción.')}finally{state.actionBusy=false}}
async function closeCurrent(){const q=state.question;if(!q||q.status!=='live')return;const{error}=await db.from('v2_questions').update({status:'closed',closed_at:now()}).eq('id',q.id).eq('session_id',state.session.id).eq('status','live');if(error)throw error}
async function launch(id){const q=state.questions.find(x=>x.id===id);if(!q)return;const{error:e1}=await db.from('v2_questions').update({status:'live',launched_at:now(),closed_at:null}).eq('id',id).eq('session_id',state.session.id);if(e1)throw e1;const{error:e2}=await db.from('v2_sessions').update({current_question_id:id,status:'live',started_at:state.session.started_at||now()}).eq('id',state.session.id).eq('teacher_id',state.user.id);if(e2)throw e2}
window.mc59Close=()=>action(closeCurrent);
window.mc59Reveal=()=>action(async()=>{if(!state.question)return;const{error}=await db.from('v2_questions').update({status:'revealed',closed_at:state.question.closed_at||now()}).eq('id',state.question.id).eq('session_id',state.session.id);if(error)throw error});
window.mc59Next=id=>action(async()=>{if(state.question?.status==='live')await closeCurrent();await launch(id)});
window.mc59Launch=id=>action(()=>launch(id));
window.mc59Room=()=>action(async()=>{const{error}=await db.from('v2_sessions').update({current_question_id:null}).eq('id',state.session.id).eq('teacher_id',state.user.id);if(error)throw error});
window.mc59Show=id=>action(async()=>{const{error}=await db.from('v2_sessions').update({current_question_id:id}).eq('id',state.session.id).eq('teacher_id',state.user.id);if(error)throw error});
window.mc59Project=()=>window.open(`./proyectar.html?code=${encodeURIComponent(state.code)}`,'tedvio_projection');
window.mc59CopyCode=async()=>{try{await navigator.clipboard.writeText(state.code);flash('Código copiado ✓')}catch{alert(`Código: ${state.code}`)}};
window.mc59ToggleRanking=()=>{state.showRanking=!state.showRanking;sessionStorage.setItem('tedvio.v59.ranking',state.showRanking?'1':'0');state.renderKey='';paint(true)};
window.mc59End=async()=>{if(!confirm('¿Finalizar la sesión y cerrar el control?'))return;await action(async()=>{const{error}=await db.from('v2_sessions').update({status:'closed',closed_at:now()}).eq('id',state.session.id).eq('teacher_id',state.user.id);if(error)throw error;state.session.status='closed';paintClosed()})};
function flash(msg){let n=document.querySelector('#mc59Flash');if(!n){n=document.createElement('div');n.id='mc59Flash';n.className='mc59-flash';document.body.appendChild(n)}n.textContent=msg;n.classList.add('show');setTimeout(()=>n.classList.remove('show'),1700)}
function paintClosed(){stopLoops();root.innerHTML=`<div class="mc59-auth"><div class="mc59-auth-card">${logo()}<span class="mc59-kicker">Sesión finalizada</span><h1>${esc(state.session?.title||'TEDVIO')}</h1><p>Código ${esc(state.code)} · La información quedó guardada.</p><button class="mc59-btn primary" onclick="location.href='/teacher'">Volver al panel docente</button><button class="mc59-btn secondary" onclick="location.href='/teacher'">Abrir reportes</button></div></div>`}
function startLoops(){stopLoops();state.poll=setInterval(()=>refresh(false),850);state.tick=setInterval(tickTimer,250)}
function stopLoops(){if(state.poll)clearInterval(state.poll);if(state.tick)clearInterval(state.tick);state.poll=state.tick=null}
window.addEventListener('online',()=>{state.offline=false;state.renderKey='';refresh(true)});window.addEventListener('offline',()=>{state.offline=true;paint(true)});document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh(true)});db.auth.onAuthStateChange((_e,s)=>{state.user=s?.user||null;if(!state.user)renderLogin()});
boot();
