import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const cfg=window.TEDVIO_CONFIG||{}; const sb=createClient(cfg.SUPABASE_URL,cfg.SUPABASE_PUBLISHABLE_KEY);
const state={quiz:null,items:[],index:0,timer:null,remaining:0,presentation:false};
const q=(s,r=document)=>r.querySelector(s); const qa=(s,r=document)=>[...r.querySelectorAll(s)];
function teacherVisible(){return location.hash.startsWith('#teacher') && q('.shell') && q('.session-panel')}
async function currentSession(){const code=q('.session-panel .code')?.textContent?.trim(); if(!code)return null; const {data}=await sb.from('sessions').select('*').eq('code',code).maybeSingle(); return data}
async function loadQuizzes(){const {data}=await sb.from('prepared_quizzes').select('*').order('created_at',{ascending:false}); return data||[]}
async function loadBank(){const {data}=await sb.from('question_bank').select('*').order('created_at',{ascending:false}); return data||[]}
async function createQuiz(){const name=prompt('Nombre del cuestionario preparado:','Repaso de clase'); if(!name)return; const bank=await loadBank(); if(!bank.length){alert('Primero guarda preguntas en tu banco.');return}
 const choices=bank.map((x,i)=>`${i+1}. ${x.prompt}`).join('\n'); const raw=prompt(`Escribe los números de las preguntas que quieres incluir, separados por comas:\n\n${choices}`,'1'); if(!raw)return;
 const idx=[...new Set(raw.split(',').map(x=>Number(x.trim())-1).filter(i=>i>=0&&i<bank.length))]; if(!idx.length)return alert('No seleccionaste preguntas válidas.');
 const {data:quiz,error}=await sb.from('prepared_quizzes').insert({name}).select().single(); if(error)return alert(error.message);
 const rows=idx.map((i,pos)=>({quiz_id:quiz.id,question_bank_id:bank[i].id,position:pos+1,timer_seconds:30})); const {error:e2}=await sb.from('prepared_quiz_items').insert(rows); if(e2)return alert(e2.message); alert('Cuestionario preparado guardado.'); }
async function selectQuiz(){const quizzes=await loadQuizzes(); if(!quizzes.length)return alert('Aún no tienes cuestionarios preparados.'); const list=quizzes.map((x,i)=>`${i+1}. ${x.name}`).join('\n'); const n=Number(prompt(`Selecciona un cuestionario:\n\n${list}`,'1'))-1; if(n<0||n>=quizzes.length)return;
 state.quiz=quizzes[n]; const {data}=await sb.from('prepared_quiz_items').select('id,position,timer_seconds,question_bank:question_bank_id(*)').eq('quiz_id',state.quiz.id).order('position'); state.items=data||[]; state.index=0; renderControl(); }
async function launchCurrent(){if(!state.items.length)return alert('Selecciona un cuestionario preparado.'); const s=await currentSession(); if(!s)return alert('No se encontró la sesión activa.'); const item=state.items[state.index],b=item.question_bank;
 const {data:last}=await sb.from('questions').select('position').eq('session_id',s.id).order('position',{ascending:false}).limit(1); const pos=(last?.[0]?.position||0)+1;
 const {data:q1,error}=await sb.from('questions').insert({session_id:s.id,position:pos,prompt:b.prompt,question_type:b.question_type,options:b.options,correct_answer:b.correct_answer,status:'live',launched_at:new Date().toISOString()}).select().single(); if(error)return alert(error.message);
 await sb.from('sessions').update({current_question_id:q1.id,status:'live',started_at:new Date().toISOString()}).eq('id',s.id); startTimer(item.timer_seconds||30); }
async function closeCurrent(){const s=await currentSession(); if(!s?.current_question_id)return; await sb.from('questions').update({status:'closed',closed_at:new Date().toISOString()}).eq('id',s.current_question_id); stopTimer();}
function next(){if(state.index<state.items.length-1){state.index++;renderControl()} }
function prev(){if(state.index>0){state.index--;renderControl()} }
function startTimer(seconds){stopTimer(); state.remaining=seconds; paintTimer(); state.timer=setInterval(async()=>{state.remaining--;paintTimer();if(state.remaining<=0){stopTimer();await closeCurrent()}},1000)}
function stopTimer(){if(state.timer)clearInterval(state.timer);state.timer=null}
function paintTimer(){const el=q('#tedvioTimer');if(el)el.textContent=state.remaining>0?`${state.remaining}s`:'—'}
function togglePresentation(){state.presentation=!state.presentation; document.body.classList.toggle('tedvio-presentation',state.presentation); renderControl()}
function renderControl(){let box=q('#tedvioEnhancements'); if(!teacherVisible()){box?.remove();return} if(!box){box=document.createElement('div');box.id='tedvioEnhancements';box.style.cssText='position:fixed;right:18px;bottom:18px;z-index:9999;background:white;border:1px solid #dbe3ef;border-radius:16px;padding:12px 14px;box-shadow:0 12px 30px rgba(0,0,0,.15);max-width:360px;font-family:inherit';document.body.appendChild(box)}
 const item=state.items[state.index]?.question_bank; box.innerHTML=`<div style="font-weight:800;margin-bottom:8px">Sesión preparada</div><div style="font-size:13px;margin-bottom:10px">${state.quiz?`${state.quiz.name} · ${state.index+1}/${state.items.length}`:'Sin cuestionario seleccionado'}</div>${item?`<div style="font-size:12px;color:#667085;margin-bottom:8px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis">${item.prompt}</div>`:''}<div style="display:flex;gap:6px;flex-wrap:wrap"><button class="btn secondary" id="tedPrev">◀</button><button class="btn primary" id="tedLaunch">Lanzar</button><button class="btn secondary" id="tedNext">▶</button><button class="btn secondary" id="tedClose">Cerrar</button><button class="btn secondary" id="tedSelect">Preparadas</button><button class="btn secondary" id="tedCreate">+ Preparar</button><button class="btn secondary" id="tedPresent">${state.presentation?'Salir proyección':'Proyectar'}</button></div><div style="margin-top:8px;font-weight:800">Tiempo: <span id="tedvioTimer">${state.remaining?state.remaining+'s':'—'}</span></div>`;
 q('#tedPrev',box).onclick=prev;q('#tedNext',box).onclick=next;q('#tedLaunch',box).onclick=launchCurrent;q('#tedClose',box).onclick=closeCurrent;q('#tedSelect',box).onclick=selectQuiz;q('#tedCreate',box).onclick=createQuiz;q('#tedPresent',box).onclick=togglePresentation; }
const style=document.createElement('style');style.textContent=`body.tedvio-presentation .topbar .topbar-actions,body.tedvio-presentation .hero button,body.tedvio-presentation #tedvioEnhancements{display:none!important}body.tedvio-presentation .content{max-width:1400px;margin:auto}body.tedvio-presentation .card{font-size:1.15em}body.tedvio-presentation .session-panel{transform:scale(1.03)}`;document.head.appendChild(style);
new MutationObserver(renderControl).observe(document.body,{childList:true,subtree:true});window.addEventListener('hashchange',renderControl);setTimeout(renderControl,500);
