import {createClient} from 'https://esm.sh/@supabase/supabase-js@2';
const cfg=window.TEDVIO_CONFIG||{},db=createClient(cfg.SUPABASE_URL,cfg.SUPABASE_PUBLISHABLE_KEY);
const VERSION='2026.08.26.63';
const S={e:null,busy:false,last:0};
const esc=(v='')=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const num=v=>v===null||v===undefined?'∞':Number(v).toLocaleString('es-MX');
const pct=(used,limit)=>limit?Math.min(100,Math.round(Number(used||0)/Number(limit)*100)):0;
function feature(k){return !!S.e?.features?.[k]}
function limit(k){return S.e?.limits?.[k]??null}
function usage(k){return Number(S.e?.usage?.[k]||0)}
function deny(title='Función Pro',msg='Esta función requiere TEDVIO Pro o Institucional.'){
 document.querySelector('#tv63Gate')?.remove();const d=document.createElement('div');d.id='tv63Gate';d.className='tv63-gate';d.innerHTML=`<div class="tv63-dialog"><span class="tv63-kicker">TEDVIO ${esc(S.e?.display_name||'Free')}</span><h3>${esc(title)}</h3><p>${esc(msg)}</p><div class="tv63-dialog-actions"><button class="b-btn secondary" id="tv63GateClose">Cerrar</button><button class="b-btn primary" id="tv63GatePlan">Ver mi plan</button></div></div>`;document.body.appendChild(d);d.querySelector('#tv63GateClose').onclick=()=>d.remove();d.querySelector('#tv63GatePlan').onclick=()=>{d.remove();openPlan()};
}
function meter(label,used,max,unit=''){const p=pct(used,max),warn=max&&used>=max;return `<div class="tv63-meter"><div><span>${esc(label)}</span><b>${Number(used||0).toLocaleString('es-MX')}${unit} / ${max===null?'∞':Number(max).toLocaleString('es-MX')+unit}</b></div><div class="tv63-track"><i class="${warn?'limit':''}" style="width:${p}%"></i></div></div>`}
function openPlan(){if(!S.e)return;document.querySelector('#tv63Plan')?.remove();const e=S.e,l=e.limits||{},u=e.usage||{},storage=Math.round(Number(u.storage_bytes||0)/1024/1024);const d=document.createElement('div');d.id='tv63Plan';d.className='tv63-gate';d.innerHTML=`<div class="tv63-plan"><div class="tv63-plan-head"><div><span class="tv63-kicker">PLAN ACTIVO</span><h2>TEDVIO ${esc(e.display_name||e.plan)}</h2><p>Uso y funciones habilitadas para tu cuenta.</p></div><button class="b-btn secondary" id="tv63PlanClose">×</button></div><div class="tv63-meters">${meter('Grupos',u.groups,l.max_groups)}${meter('Sesiones este mes',u.sessions_month,l.max_live_sessions_month)}${meter('Almacenamiento',storage,l.max_storage_mb,' MB')}</div><div class="tv63-features"><div class="${feature('live_sessions')?'on':''}">✓ Sesiones en vivo</div><div class="${feature('qr_attendance')?'on':''}">✓ Asistencia QR</div><div class="${feature('live_ranking')?'on':''}">✓ Ranking en vivo</div><div class="${feature('omr')?'on':'off'}">${feature('omr')?'✓':'🔒'} Exámenes OMR</div><div class="${feature('analytics_pro')?'on':'off'}">${feature('analytics_pro')?'✓':'🔒'} Analítica Pro</div><div class="${feature('exports')?'on':'off'}">${feature('exports')?'✓':'🔒'} Exportaciones avanzadas</div></div><div class="tv63-plan-note">Límite por grupo: <b>${num(l.max_students_per_group)} alumnos</b>. Los límites se validan también en el servidor.</div></div>`;document.body.appendChild(d);d.querySelector('#tv63PlanClose').onclick=()=>d.remove();}
window.tv63OpenPlan=openPlan;
function patch(name,guard){const fn=window[name];if(typeof fn!=='function'||fn.__tv63)return;const w=function(...args){const r=guard(...args);if(r===false)return;return fn.apply(this,args)};Object.assign(w,fn);w.__tv63=true;w.__tv63Original=fn;window[name]=w}
function installPatches(){
 patch('betaNewSession',()=>{const m=limit('max_live_sessions_month');if(m!==null&&usage('sessions_month')>=m){deny('Límite mensual alcanzado',`Tu plan ${S.e.display_name} permite ${m} sesiones nuevas por mes.`);return false}});
 patch('gaNewGroup',()=>{const m=limit('max_groups');if(m!==null&&usage('groups')>=m){deny('Límite de grupos alcanzado',`Tu plan ${S.e.display_name} permite hasta ${m} grupos.`);return false}});
 for(const n of ['peOpenHome','peNewExam','ga360OpenExams','tvPilotOpenExamForGroup'])patch(n,()=>{if(!feature('omr')){deny('Exámenes OMR','OMR está disponible en TEDVIO Pro e Institucional.');return false}});
 patch('ga360Tab',k=>{if(k==='analytics'&&!feature('analytics_pro')){deny('Analítica Pro','El análisis académico avanzado está disponible en TEDVIO Pro e Institucional.');return false}});
 for(const n of ['ga61Excel','ga61Pdf','peExportResults'])patch(n,()=>{if(!feature('exports')){deny('Exportación avanzada','Las exportaciones avanzadas están disponibles en TEDVIO Pro e Institucional.');return false}});
}
function installUi(){const a=document.querySelector('.b-top-actions');if(a){let b=a.querySelector('#tv63PlanBtn');if(!b){b=document.createElement('button');b.id='tv63PlanBtn';b.className='b-btn secondary tv63-plan-btn';b.onclick=openPlan;a.insertBefore(b,a.firstChild)}b.textContent=`${String(S.e?.display_name||S.e?.plan||'Free').toUpperCase()}`;b.dataset.plan=S.e?.plan||'free'}const paper=document.querySelector('#tedvioPaperBtn');if(paper){if(!feature('omr')){paper.classList.add('tv63-locked');paper.textContent='Exámenes · PRO';paper.onclick=()=>deny('Exámenes OMR','OMR está disponible en TEDVIO Pro e Institucional.')}else{paper.classList.remove('tv63-locked');paper.textContent='Exámenes';if(typeof window.peOpenHome==='function')paper.onclick=window.peOpenHome}}document.documentElement.dataset.tedvioPlan=S.e?.plan||'free'}
async function load(force=false){if(S.busy)return;const now=Date.now();if(!force&&now-S.last<20000)return;S.busy=true;S.last=now;try{const{data:{session}}=await db.auth.getSession();if(!session?.user){S.e=null;return}const{data,error}=await db.rpc('tedvio_current_entitlements');if(error){console.warn('TEDVIO v63 entitlements',error.message);return}S.e=data;window.TEDVIO_ENTITLEMENTS=data;window.dispatchEvent(new CustomEvent('tedvio:entitlements',{detail:data}));installPatches();installUi()}finally{S.busy=false}}
new MutationObserver(()=>{if(S.e){installPatches();installUi()}}).observe(document.querySelector('#betaApp'),{childList:true,subtree:true});
document.addEventListener('visibilitychange',()=>{if(!document.hidden)load(true)});window.addEventListener('online',()=>load(true));db.auth.onAuthStateChange(()=>setTimeout(()=>load(true),150));setInterval(()=>load(false),60000);load(true);
