import{createClient}from'https://esm.sh/@supabase/supabase-js@2';
const cfg=window.TEDVIO_CONFIG||{},db=createClient(cfg.SUPABASE_URL,cfg.SUPABASE_PUBLISHABLE_KEY);
const VERSION='2026.08.26.68';
const S={user:null,snap:null,groups:[],bank:[],admin:false,funnel:null,busy:false,autoShown:false,createdIds:new Set(),courseGroupId:null,mode:'overview'};
const esc=(v='')=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const norm=v=>String(v??'').trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
const teacherRoute=()=>!location.hash.startsWith('#join')&&!location.hash.startsWith('#student')&&!document.querySelector('.b-login');
const score=()=>Number(S.snap?.score||0);
const complete=()=>score()>=5;
async function me(){if(S.user)return S.user;const{data:{session}}=await db.auth.getSession();S.user=session?.user||null;return S.user}
async function track(type,context={}){if(!S.user)return;try{await db.from('tedvio_activation_events').insert({user_id:S.user.id,event_type:type,context})}catch{}}
async function trackDaily(){if(!S.user)return;const d=new Date().toLocaleDateString('en-CA'),k=`tedvio.v68.activeDay.${S.user.id}`;if(localStorage.getItem(k)===d)return;localStorage.setItem(k,d);await track('workspace_opened',{version:VERSION,path:location.pathname})}
async function saveProgress(step,add=[],patch={}){if(!S.user)return;const all=[...new Set([...(S.snap?.completed_steps||[]),...add])];const row={user_id:S.user.id,last_step:step,completed_steps:all,updated_at:new Date().toISOString(),...patch};const{error}=await db.from('tedvio_onboarding_progress').upsert(row,{onConflict:'user_id'});if(error)throw error}
async function load(){const u=await me();if(!u||!teacherRoute())return;const[s,g,b,r]=await Promise.all([
 db.rpc('tedvio_activation_snapshot_v68'),
 db.from('v2_groups').select('id,name,group_name,subject,term,university,program,is_demo').eq('teacher_id',u.id).eq('is_demo',false).order('created_at',{ascending:true}),
 db.from('v2_question_bank').select('id,prompt,question_type,subject,topic,folder,archived').eq('teacher_id',u.id).eq('archived',false).neq('folder','TEDVIO Demo').order('updated_at',{ascending:false}).limit(100),
 db.rpc('tedvio_my_admin_role')
]);if(s.error)throw s.error;S.snap=s.data||{};S.groups=g.data||[];S.bank=b.data||[];S.admin=r.data==='admin';if(S.admin){const f=await db.rpc('tedvio_activation_funnel_v68');S.funnel=f.error?null:f.data}else S.funnel=null;installNav();installBanner();await trackDaily()}
function nextAction(){const z=S.snap||{};if(!z.programs)return['course','Configura universidad y programa'];if(!z.groups)return['course','Crea tu primer grupo'];if(!z.students)return['students','Agrega tu lista de alumnos'];if(!z.questions)return['question','Crea tu primera actividad'];if(!z.sessions)return['ready','Inicia tu primera clase'];return['overview','Todo listo para trabajar']}
function installNav(){const bar=document.querySelector('.b-top-actions');if(!bar)return;let b=bar.querySelector('#tv68OnboardingBtn');if(!b){b=document.createElement('button');b.id='tv68OnboardingBtn';b.className='b-btn dark tv68-nav-btn';b.onclick=()=>open('overview');const primary=bar.querySelector('.b-btn.primary');primary?bar.insertBefore(b,primary):bar.appendChild(b)}b.textContent=complete()?'✓ Configurado':`Inicio ${score()}/5`;b.classList.toggle('done',complete())}
function installBanner(){document.querySelector('#tv68ActivationBanner')?.remove();if(complete()||document.querySelector('#tv68Overlay')||document.querySelector('#sessionMain'))return;const host=document.querySelector('.b-main');if(!host)return;const[m,label]=nextAction(),d=document.createElement('div');d.id='tv68ActivationBanner';d.className='tv68-banner';d.innerHTML=`<div><span>CONFIGURACIÓN ${score()}/5</span><b>${esc(label)}</b><small>TEDVIO te lleva al siguiente paso sin perder lo que ya hiciste.</small></div><button class="b-btn primary">Continuar</button>`;d.querySelector('button').onclick=()=>open(m);host.prepend(d)}
function overlay(html){document.querySelector('#tv68Overlay')?.remove();const d=document.createElement('div');d.id='tv68Overlay';d.className='tv68-overlay';d.innerHTML=`<div class="tv68-modal">${html}</div>`;document.body.appendChild(d);d.addEventListener('mousedown',e=>{if(e.target===d)close()});return d}
function close(){document.querySelector('#tv68Overlay')?.remove();installBanner()}
const checklist=()=>{const z=S.snap||{},rows=[['programs','Universidad y programa',z.programs>0],['groups','Primer grupo',z.groups>0],['students','Lista de alumnos',z.students>0],['questions','Primera actividad',z.questions>0],['sessions','Primera clase',z.sessions>0]];return`<div class="tv68-checklist">${rows.map(([k,t,ok],i)=>`<div class="${ok?'done':''}"><span>${ok?'✓':i+1}</span><b>${t}</b><small>${ok?'Completado':'Pendiente'}</small></div>`).join('')}</div>`}
function funnelHtml(){if(!S.admin||!S.funnel)return'';const f=S.funnel;return`<section class="tv68-funnel"><div class="tv68-section-title"><div><span>ACTIVACIÓN · ADMIN</span><h3>Embudo de adopción</h3></div></div><div class="tv68-funnel-grid">${[['Cuentas',f.accounts],['Vieron onboarding',f.onboarding_seen],['Curso creado',f.course_created],['Alumnos',f.students_imported],['Pregunta',f.question_created],['1ª sesión',f.first_session],['Completaron',f.completed],['Volvieron ≥2 días',f.returned_2_days]].map(([l,v])=>`<div><b>${Number(v||0)}</b><span>${l}</span></div>`).join('')}</div></section>`}
function shell(title,sub,body,step=''){return`<header class="tv68-head"><div><span>TEDVIO v68 · PRODUCT ACTIVATION${step?` · ${step}`:''}</span><h2>${esc(title)}</h2><p>${esc(sub)}</p></div><button class="tv68-x" onclick="tv68Close()">×</button></header>${body}`}
function overviewHtml(){const[next,label]=nextAction();return shell('Empieza en minutos','Configura tu curso o conoce TEDVIO con un entorno de demostración.',`<div class="tv68-progress"><div><span>Tu configuración</span><b>${score()}/5</b></div><i><b style="width:${score()*20}%"></b></i></div>${checklist()}<div class="tv68-choice"><button onclick="tv68Open('${next}')"><span>Configurar mi curso</span><b>${complete()?'Revisar configuración':esc(label)}</b><small>Usa tus datos reales y deja tu primera clase lista.</small></button><button class="demo" onclick="tv68Demo()"><span>Demo de 2 minutos</span><b>Probar TEDVIO ahora</b><small>10 alumnos, 5 preguntas y un lobby real. No consume tu plan.</small></button></div>${funnelHtml()}${!complete()?'<button class="tv68-later" onclick="tv68Dismiss()">Ahora no · mostrarme el acceso desde Inicio</button>':''}`)}
function courseHtml(){const g=S.groups[0]||{};return shell('Tu primer curso','Una sola pantalla crea la estructura académica canónica de TEDVIO.',`<div class="tv68-form"><label>Universidad<input id="tv68University" value="${esc(g.university||'')}" placeholder="Ej. Universidad Autónoma de Sinaloa"></label><label>Programa académico<input id="tv68Program" value="${esc(g.program||'')}" placeholder="Ej. Medicina General"></label><div class="tv68-two"><label>Materia<input id="tv68Subject" value="${esc(g.subject||'')}" placeholder="Ej. Farmacología"></label><label>Grupo<input id="tv68Group" value="${esc(g.group_name||g.name||'')}" placeholder="Ej. III-8"></label></div><label>Periodo / ciclo<input id="tv68Term" value="${esc(g.term||'')}" placeholder="Ej. Agosto–Diciembre 2026"></label><div class="tv68-actions"><button class="b-btn secondary" onclick="tv68Open('overview')">Atrás</button><button class="b-btn primary" onclick="tv68SaveCourse()">Guardar y continuar</button></div></div>`,'PASO 1 DE 5')}
function groupOptions(){return S.groups.map(g=>`<option value="${g.id}" ${S.courseGroupId===g.id?'selected':''}>${esc(g.group_name||g.name)}${g.subject?' · '+esc(g.subject):''}</option>`).join('')}
function studentsHtml(){if(!S.groups.length)return courseHtml();return shell('Agrega tus alumnos','Pega matrícula y nombre desde Excel o carga un CSV. TEDVIO valida el roster antes de guardarlo.',`<div class="tv68-form"><label>Grupo<select id="tv68StudentGroup">${groupOptions()}</select></label><label>Lista de alumnos<textarea id="tv68Roster" rows="10" placeholder="001, Ana López\n002, Carlos Pérez\n003, María García"></textarea></label><div class="tv68-roster-tools"><label class="b-btn secondary">Cargar CSV<input id="tv68RosterFile" type="file" accept=".csv,.txt" hidden></label><span>Formato: matrícula, nombre. También acepta tabulador o punto y coma.</span></div><div class="tv68-actions"><button class="b-btn secondary" onclick="tv68Open('course')">Atrás</button><button class="b-btn secondary" onclick="tv68Open('question')">Lo haré después</button><button class="b-btn primary" onclick="tv68SaveStudents()">Importar y continuar</button></div></div>`,'PASO 2 DE 5')}
function questionHtml(){const existing=S.bank.slice(0,6);return shell('Crea tu primera actividad','Puedes crear una pregunta ahora o reutilizar una que ya exista en tu banco.',`<div class="tv68-template-row"><button onclick="tv68Template('scale')"><b>Encuesta inicial</b><span>Escala 1–5</span></button><button onclick="tv68Template('open')"><b>Pregunta de apertura</b><span>Respuesta abierta</span></button><button onclick="tv68Template('mc')"><b>Opción múltiple</b><span>Con calificación</span></button></div><div class="tv68-form"><label>Tipo<select id="tv68QType" onchange="tv68QTypeChanged()"><option value="multiple_choice">Opción múltiple</option><option value="poll">Encuesta</option><option value="scale_5">Escala 1–5</option><option value="open_text">Respuesta abierta</option></select></label><label>Pregunta<textarea id="tv68QPrompt" rows="4" placeholder="Escribe tu pregunta"></textarea></label><div id="tv68Options"><div class="tv68-two"><label>Opción A<input id="tv68A"></label><label>Opción B<input id="tv68B"></label><label>Opción C<input id="tv68C"></label><label>Opción D<input id="tv68D"></label></div><label id="tv68CorrectWrap">Respuesta correcta<select id="tv68Correct"><option value="0">A</option><option value="1">B</option><option value="2">C</option><option value="3">D</option></select></label></div><div class="tv68-actions"><button class="b-btn secondary" onclick="tv68Open('students')">Atrás</button><button class="b-btn primary" onclick="tv68SaveQuestion()">Guardar actividad</button></div></div>${existing.length?`<div class="tv68-existing"><b>O usa una pregunta existente</b>${existing.map(q=>`<button onclick="tv68UseExisting('${q.id}')"><span>${esc(q.prompt)}</span><small>${esc(q.subject||q.question_type)}</small></button>`).join('')}</div>`:''}`,'PASO 3 DE 5')}
function readyHtml(){if(!S.groups.length)return courseHtml();if(!S.bank.length)return questionHtml();const defaults=S.createdIds.size?S.createdIds:new Set(S.bank.slice(0,3).map(x=>x.id));return shell('Todo listo para tu primera clase','Elige el grupo y las preguntas. TEDVIO creará el lobby con código de acceso.',`<div class="tv68-form"><label>Grupo<select id="tv68LaunchGroup">${groupOptions()}</select></label><div class="tv68-picks"><b>Preguntas para la sesión</b>${S.bank.slice(0,12).map((q,i)=>`<label><input class="tv68BankPick" type="checkbox" value="${q.id}" ${defaults.has(q.id)?'checked':''}><span><strong>${esc(q.prompt)}</strong><small>${esc(q.subject||'Banco')} · ${esc(q.question_type)}</small></span></label>`).join('')}</div><div class="tv68-actions"><button class="b-btn secondary" onclick="tv68Open('question')">Atrás</button><button class="b-btn primary" onclick="tv68Launch()">Iniciar mi primera clase</button></div></div>`,'PASO 4–5 DE 5')}
function render(mode='overview'){S.mode=mode;let html=overviewHtml();if(mode==='course')html=courseHtml();else if(mode==='students')html=studentsHtml();else if(mode==='question')html=questionHtml();else if(mode==='ready')html=readyHtml();overlay(html);if(mode==='students')document.querySelector('#tv68RosterFile')?.addEventListener('change',async e=>{const f=e.target.files?.[0];if(f)document.querySelector('#tv68Roster').value=await f.text()});if(mode==='question')qTypeChanged()}
async function open(mode='overview'){if(S.busy)return;S.busy=true;try{await load();if(!S.snap)return;await track('onboarding_viewed',{mode});render(mode)}catch(e){console.error('TEDVIO v68',e);alert(e.message||'No pude abrir la configuración.')}finally{S.busy=false}}
async function dismiss(){try{await saveProgress(S.snap?.last_step||'welcome',[],{dismissed:true});await track('onboarding_dismissed');close();await load()}catch(e){alert(e.message)}}
async function saveCourse(){const university=document.querySelector('#tv68University').value.trim(),program=document.querySelector('#tv68Program').value.trim(),subject=document.querySelector('#tv68Subject').value.trim(),group=document.querySelector('#tv68Group').value.trim(),term=document.querySelector('#tv68Term').value.trim();if(!university||!program||!subject||!group)return alert('Completa universidad, programa, materia y grupo.');try{let{data:u,error}=await db.from('v2_universities').select('id').eq('teacher_id',S.user.id).eq('name',university).maybeSingle();if(error)throw error;if(!u){const r=await db.from('v2_universities').insert({teacher_id:S.user.id,name:university}).select('id').single();if(r.error)throw r.error;u=r.data}let{data:p,error:pe}=await db.from('v2_programs').select('id').eq('teacher_id',S.user.id).eq('university_id',u.id).eq('name',program).maybeSingle();if(pe)throw pe;if(!p){const r=await db.from('v2_programs').insert({teacher_id:S.user.id,university_id:u.id,name:program}).select('id').single();if(r.error)throw r.error;p=r.data}let{data:g,error:ge}=await db.from('v2_groups').select('id').eq('teacher_id',S.user.id).eq('program_id',p.id).eq('name',group).maybeSingle();if(ge)throw ge;if(g){const r=await db.from('v2_groups').update({subject,term:term||null,university,program,group_name:group,school_cycle:term||null}).eq('id',g.id).eq('teacher_id',S.user.id).select('id').single();if(r.error)throw r.error;g=r.data}else{const r=await db.from('v2_groups').insert({teacher_id:S.user.id,program_id:p.id,name:group,subject,term:term||null,university,program,group_name:group,school_cycle:term||null,is_demo:false}).select('id').single();if(r.error)throw r.error;g=r.data}S.courseGroupId=g.id;await track('course_created',{group_id:g.id,subject});await saveProgress('students',['course']);await load();render('students')}catch(e){console.error(e);alert(e.message||'No pude crear el curso.')}}
function parseRoster(text){const rows=[];for(const line of String(text||'').split(/\r?\n/)){const x=line.trim();if(!x)continue;const p=x.split(/\t|;|,/).map(v=>v.trim()).filter(Boolean);if(p.length<2)continue;if(/matr|enroll|codigo|código/i.test(p[0])&&/nombre|alumno/i.test(p.slice(1).join(' ')))continue;rows.push({enrollment:p[0],full_name:p.slice(1).join(' ')})}const map=new Map();rows.forEach(r=>map.set(norm(r.enrollment),r));return[...map.values()]}
async function saveStudents(){const gid=document.querySelector('#tv68StudentGroup').value,rows=parseRoster(document.querySelector('#tv68Roster').value);if(!gid)return alert('Selecciona un grupo.');if(!rows.length)return alert('Pega al menos una fila con matrícula y nombre.');try{const ex=await db.from('v2_group_students').select('id,enrollment').eq('group_id',gid).eq('teacher_id',S.user.id);if(ex.error)throw ex.error;const by=new Map((ex.data||[]).map(x=>[norm(x.enrollment),x]));const fresh=[];for(const r of rows){const old=by.get(norm(r.enrollment));if(old){const u=await db.from('v2_group_students').update({full_name:r.full_name,active:true}).eq('id',old.id).eq('teacher_id',S.user.id);if(u.error)throw u.error}else fresh.push({group_id:gid,teacher_id:S.user.id,enrollment:r.enrollment,full_name:r.full_name,active:true})}if(fresh.length){const ins=await db.from('v2_group_students').insert(fresh);if(ins.error)throw ins.error}await track('students_imported',{group_id:gid,count:rows.length});await saveProgress('question',['students']);await load();render('question')}catch(e){console.error(e);alert(e.message||'No pude importar el roster.')}}
function qTypeChanged(){const t=document.querySelector('#tv68QType')?.value,box=document.querySelector('#tv68Options'),correct=document.querySelector('#tv68CorrectWrap');if(!box)return;box.style.display=['multiple_choice','poll'].includes(t)?'block':'none';if(correct)correct.style.display=t==='multiple_choice'?'block':'none'}
function template(kind){const type=document.querySelector('#tv68QType'),prompt=document.querySelector('#tv68QPrompt'),subject=S.groups.find(g=>g.id===S.courseGroupId)?.subject||S.groups[0]?.subject||'esta materia';if(kind==='scale'){type.value='scale_5';prompt.value=`Del 1 al 5, ¿qué tan familiarizado estás con los temas de ${subject}?`}else if(kind==='open'){type.value='open_text';prompt.value=`¿Qué tema de ${subject} te gustaría comprender mejor?`}else{type.value='multiple_choice';prompt.value='';document.querySelector('#tv68A').value='';document.querySelector('#tv68B').value='';document.querySelector('#tv68C').value='';document.querySelector('#tv68D').value=''}qTypeChanged();prompt.focus()}
async function saveQuestion(){const t=document.querySelector('#tv68QType').value,prompt=document.querySelector('#tv68QPrompt').value.trim();if(!prompt)return alert('Escribe la pregunta.');let options=[],correct=null;if(['multiple_choice','poll'].includes(t)){options=['tv68A','tv68B','tv68C','tv68D'].map(id=>document.querySelector('#'+id).value.trim()).filter(Boolean);if(options.length<2)return alert('Escribe al menos dos opciones.');if(t==='multiple_choice')correct=options[Number(document.querySelector('#tv68Correct').value)]??options[0]}else if(t==='scale_5')options=['1','2','3','4','5'];const subject=S.groups.find(g=>g.id===S.courseGroupId)?.subject||S.groups[0]?.subject||null;try{const r=await db.from('v2_question_bank').insert({teacher_id:S.user.id,title:prompt.slice(0,90),subject,topic:'Inicio del curso',question_type:t,prompt,options,correct_answer:correct,explanation:null,difficulty:'baja',folder:'Mi primer curso',tags:['onboarding'],bloom:t==='open_text'?'crear':'comprender'}).select('id').single();if(r.error)throw r.error;S.createdIds.add(r.data.id);await track('question_created',{bank_id:r.data.id,type:t});await saveProgress('ready',['question']);await load();render('ready')}catch(e){console.error(e);alert(e.message||'No pude guardar la actividad.')}}
async function useExisting(id){S.createdIds.add(id);await saveProgress('ready',['question']);await track('question_selected_existing',{bank_id:id});render('ready')}
async function launch(){const gid=document.querySelector('#tv68LaunchGroup').value,ids=[...document.querySelectorAll('.tv68BankPick:checked')].map(x=>x.value);if(!gid||!ids.length)return alert('Selecciona grupo y al menos una pregunta.');try{const r=await db.rpc('tedvio_launch_first_session_v68',{p_group_id:gid,p_bank_ids:ids});if(r.error)throw r.error;await load();close();if(window.betaOpenSession)await window.betaOpenSession(r.data.session_id);showCoach(r.data,false)}catch(e){console.error(e);alert(e.message||'No pude iniciar la clase.')}}
async function demo(){if(S.busy)return;S.busy=true;try{const r=await db.rpc('tedvio_create_demo_v68');if(r.error)throw r.error;await load();close();if(window.betaOpenSession)await window.betaOpenSession(r.data.session_id);showCoach(r.data,true)}catch(e){console.error(e);alert(e.message||'No pude preparar la demo.')}finally{S.busy=false}}
function showCoach(data,isDemo){document.querySelector('#tv68Coach')?.remove();const d=document.createElement('div');d.id='tv68Coach';d.className='tv68-coach';d.innerHTML=`<button class="tv68-coach-x">×</button><span>${isDemo?'DEMO LISTA':'PRIMERA CLASE LISTA'}</span><h3>${isDemo?'Tu entorno de práctica está activo':'Comparte el código con tus alumnos'}</h3><div class="tv68-coach-code">${esc(data.code)}</div><p>${isDemo?'El grupo incluye 10 alumnos demo y 5 preguntas. Entra como alumno para comprobar el flujo completo.':'El lobby ya está preparado; los alumnos aparecerán conforme ingresen.'}</p><div><button id="tv68StudentView">Probar como alumno</button><button id="tv68Projection">Abrir proyección</button></div>`;document.body.appendChild(d);d.querySelector('.tv68-coach-x').onclick=()=>d.remove();d.querySelector('#tv68StudentView').onclick=()=>window.open(`./beta.html#join?code=${encodeURIComponent(data.code)}`,'_blank');d.querySelector('#tv68Projection').onclick=()=>window.open(`./proyectar.html?code=${encodeURIComponent(data.code)}`,'_blank')}
new MutationObserver(()=>{if(teacherRoute()){installNav();installBanner()}}).observe(document.documentElement,{childList:true,subtree:true});
async function boot(){try{const u=await me();if(!u||!teacherRoute())return;await load();setTimeout(()=>{if(!S.autoShown&&score()<5&&!S.snap?.dismissed&&!document.querySelector('#sessionMain')){S.autoShown=true;open(S.snap?.last_step&&S.snap.last_step!=='welcome'?S.snap.last_step:'overview')}},1200)}catch(e){console.warn('TEDVIO Onboarding v68',e)}}
db.auth.onAuthStateChange((_e,s)=>{S.user=s?.user||null;if(S.user)setTimeout(boot,300)});window.addEventListener('hashchange',()=>setTimeout(boot,250));setTimeout(boot,450);
window.tv68Open=open;window.tv68Close=close;window.tv68Dismiss=dismiss;window.tv68SaveCourse=saveCourse;window.tv68SaveStudents=saveStudents;window.tv68QTypeChanged=qTypeChanged;window.tv68Template=template;window.tv68SaveQuestion=saveQuestion;window.tv68UseExisting=useExisting;window.tv68Launch=launch;window.tv68Demo=demo;window.__TEDVIO_ONBOARDING68__={version:VERSION,open,refresh:load};