import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const cfg=window.TEDVIO_CONFIG||{},sb=createClient(cfg.SUPABASE_URL,cfg.SUPABASE_PUBLISHABLE_KEY);
const state={quiz:null,items:[],index:0,visible:false};
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function sessionCode(){return document.querySelector('.session-panel .code')?.textContent?.trim()||null}
function teacherActive(){return location.hash.startsWith('#teacher')&&!!sessionCode()}
function ensureStyles(){if(document.querySelector('#tedvioPreparedStyles'))return;const s=document.createElement('style');s.id='tedvioPreparedStyles';s.textContent=`#tedvioPreparedBtn{position:fixed;left:18px;bottom:18px;z-index:9000;border:0;border-radius:999px;padding:12px 18px;background:#fff;color:#0A1B3D;font-weight:800;box-shadow:0 10px 28px rgba(0,0,0,.18);cursor:pointer;border:1px solid #dbe3ef}#tedvioPreparedPanel{position:fixed;left:18px;bottom:74px;z-index:8999;width:min(430px,calc(100vw - 36px));max-height:72vh;overflow:auto;background:#fff;border:1px solid #dbe3ef;border-radius:18px;padding:16px;box-shadow:0 16px 40px rgba(0,0,0,.18)}#tedvioPreparedPanel h3{margin:0 0 4px}.tp-sub{font-size:12px;color:#667085;margin-bottom:12px}.tp-row{display:flex;gap:8px;flex-wrap:wrap}.tp-card{padding:10px 0;border-top:1px solid #eef2f7}.tp-close{float:right;border:0;background:transparent;font-size:20px}.tp-list{display:grid;gap:8px;margin:10px 0}.tp-check{display:grid;grid-template-columns:24px 1fr;gap:8px;align-items:flex-start;padding:8px;border:1px solid #eef2f7;border-radius:10px}.tp-index{font-size:12px;color:#667085;margin-bottom:8px}.tp-current{font-weight:800;margin:6px 0 12px}@media(max-width:600px){#tedvioPreparedBtn{left:12px;bottom:12px;padding:10px 14px;font-size:14px}#tedvioPreparedPanel{left:10px;right:10px;bottom:64px;width:auto;max-height:68vh}}`;document.head.appendChild(s)}
function clear(){document.querySelector('#tedvioPreparedBtn')?.remove();document.querySelector('#tedvioPreparedPanel')?.remove();state.visible=false}
function ensureButton(){if(!teacherActive()){clear();return}if(document.querySelector('#tedvioPreparedBtn'))return;const b=document.createElement('button');b.id='tedvioPreparedBtn';b.textContent='📚 Sesión preparada';b.onclick=()=>{state.visible=!state.visible;renderPanel()};document.body.appendChild(b)}
async function getSession(){const code=sessionCode();if(!code)return null;const {data}=await sb.from('sessions').select('*').eq('code',code).maybeSingle();return data}
async function loadQuizItems(id){const {data,error}=await sb.from('prepared_quiz_items').select('id,position,timer_seconds,question_bank:question_bank_id(*)').eq('quiz_id',id).order('position');if(error)throw error;state.items=data||[];state.index=0}
async function chooseQuiz(){const {data,error}=await sb.from('prepared_quizzes').select('*').order('created_at',{ascending:false});if(error)return alert(error.message);const quizzes=data||[];if(!quizzes.length)return alert('Aún no tienes sesiones preparadas.');const list=quizzes.map((q,i)=>`${i+1}. ${q.name}`).join('\n');const n=Number(prompt(`Selecciona una sesión preparada:\n\n${list}`,'1'))-1;if(n<0||n>=quizzes.length)return;state.quiz=quizzes[n];await loadQuizItems(state.quiz.id);renderPanel()}
async function createPrepared(){const {data:bank,error}=await sb.from('question_bank').select('*').order('created_at',{ascending:false});if(error)return alert(error.message);if(!bank?.length)return alert('Primero guarda preguntas en el banco.');let panel=document.querySelector('#tedvioPreparedPanel');if(!panel)return;panel.innerHTML=`<button class="tp-close">×</button><h3>Crear sesión preparada</h3><div class="tp-sub">Selecciona las preguntas en el orden en que quieres usarlas.</div><div class="field"><label>Nombre</label><input id="tpName" placeholder="Repaso de clase"></div><div class="tp-list">${bank.map((q,i)=>`<label class="tp-check"><input type="checkbox" value="${q.id}" data-pos="${i}"><span><b>${esc(q.prompt)}</b><br><small>${esc(q.subject||'Sin materia')} · ${esc(q.topic||'Sin tema')}</small></span></label>`).join('')}</div><button class="btn primary" id="tpSave">Guardar sesión preparada</button>`;panel.querySelector('.tp-close').onclick=()=>{state.visible=false;panel.remove()};panel.querySelector('#tpSave').onclick=async()=>{const name=panel.querySelector('#tpName').value.trim();const ids=[...panel.querySelectorAll('input[type=checkbox]:checked')].map(x=>x.value);if(!name)return alert('Escribe un nombre.');if(!ids.length)return alert('Selecciona al menos una pregunta.');const {data:quiz,error:qerr}=await sb.from('prepared_quizzes').insert({name}).select().single();if(qerr)return alert(qerr.message);const rows=ids.map((id,i)=>({quiz_id:quiz.id,question_bank_id:id,position:i+1,timer_seconds:30}));const {error:ierr}=await sb.from('prepared_quiz_items').insert(rows);if(ierr)return alert(ierr.message);state.quiz=quiz;await loadQuizItems(quiz.id);renderPanel()}}
async function launchItem(index){if(index<0||index>=state.items.length)return;state.index=index;const s=await getSession();if(!s)return alert('No se encontró la sesión activa.');const item=state.items[state.index],q=item.question_bank;if(!q)return alert('No se encontró la pregunta.');const {data:last}=await sb.from('questions').select('position').eq('session_id',s.id).order('position',{ascending:false}).limit(1);const pos=(last?.[0]?.position||0)+1;const {data:newq,error}=await sb.from('questions').insert({session_id:s.id,position:pos,prompt:q.prompt,question_type:q.question_type,options:q.options,correct_answer:q.correct_answer,status:'live',launched_at:new Date().toISOString()}).select().single();if(error)return alert(error.message);await sb.from('sessions').update({current_question_id:newq.id,status:'live',started_at:new Date().toISOString()}).eq('id',s.id);state.visible=false;renderPanel()}
async function nextAndLaunch(){if(!state.items.length)return alert('Selecciona una sesión preparada.');if(state.index>=state.items.length-1)return alert('Llegaste a la última pregunta.');await launchItem(state.index+1)}
function prev(){if(state.index>0){state.index--;renderPanel()}}
function next(){if(state.index<state.items.length-1){state.index++;renderPanel()}}
function renderPanel(){document.querySelector('#tedvioPreparedPanel')?.remove();if(!state.visible||!teacherActive())return;const p=document.createElement('section');p.id='tedvioPreparedPanel';const current=state.items[state.index]?.question_bank;p.innerHTML=`<button class="tp-close">×</button><h3>📚 Sesión preparada</h3><div class="tp-sub">Flujo: lanzar → responder → cerrar → ranking → siguiente.</div>${state.quiz?`<div class="tp-index">${esc(state.quiz.name)} · ${state.items.length?state.index+1:0}/${state.items.length}</div><div class="tp-current">${current?esc(current.prompt):'Sin preguntas'}</div>`:'<div class="tp-current">No hay sesión preparada seleccionada.</div>'}<div class="tp-row"><button class="btn secondary" id="tpChoose">Abrir</button><button class="btn secondary" id="tpCreate">+ Crear</button>${state.items.length?`<button class="btn secondary" id="tpPrev">◀</button><button class="btn primary" id="tpLaunch">Lanzar</button><button class="btn secondary" id="tpNext">▶</button><button class="btn primary" id="tpNextLaunch">Siguiente y lanzar</button>`:''}</div>`;document.body.appendChild(p);p.querySelector('.tp-close').onclick=()=>{state.visible=false;p.remove()};p.querySelector('#tpChoose').onclick=chooseQuiz;p.querySelector('#tpCreate').onclick=createPrepared;p.querySelector('#tpPrev')&&(p.querySelector('#tpPrev').onclick=prev);p.querySelector('#tpNext')&&(p.querySelector('#tpNext').onclick=next);p.querySelector('#tpLaunch')&&(p.querySelector('#tpLaunch').onclick=()=>launchItem(state.index));p.querySelector('#tpNextLaunch')&&(p.querySelector('#tpNextLaunch').onclick=nextAndLaunch)}
ensureStyles();setInterval(()=>{ensureButton();if(state.visible&&!document.querySelector('#tedvioPreparedPanel'))renderPanel()},1200);window.addEventListener('hashchange',()=>setTimeout(ensureButton,100));setTimeout(ensureButton,600);