import {createClient} from 'https://esm.sh/@supabase/supabase-js@2';

const cfg=window.TEDVIO_CONFIG||{};
const sb=createClient(cfg.SUPABASE_URL,cfg.SUPABASE_PUBLISHABLE_KEY);
const root=document.querySelector('#projectionApp');
const esc=(v='')=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#039;'}[m]));
const typeLabel={multiple_choice:'Opción múltiple',multiple_select:'Selección múltiple',true_false:'Verdadero / Falso',open_text:'Respuesta abierta',numeric:'Respuesta numérica',poll:'Encuesta',scale_5:'Escala 1–5',ordering:'Ordenar pasos',hotspot:'Zona de imagen'};
let code=new URLSearchParams(location.search).get('code')||'';
let timer=null,busy=false,lastGood=null,currentScreen='',lastPeople=new Set(),lastPeopleKey='',lastRankKey='';

function logo(){return '<img class="pj-logo" src="./assets/tedvio_official_horizontal.svg?v=53" alt="TEDVIO">'}
function entry(){currentScreen='entry';root.innerHTML=`<div class="pj-entry"><div class="pj-card">${logo()}<h1>Pantalla de proyección</h1><p>Escribe el código de la sesión.</p><input id="pjCode" inputmode="numeric" maxlength="6" value="${esc(code)}"><button id="pjGo">Abrir proyección</button></div></div>`;document.querySelector('#pjGo').onclick=()=>{code=document.querySelector('#pjCode').value.trim();if(code.length!==6)return;history.replaceState(null,'',`?code=${code}`);start()}}

async function fetchState(){
  const {data:meta,error:metaError}=await sb.rpc('v2_public_session_meta',{p_code:code});
  if(metaError)throw metaError;
  const s=meta?.[0];if(!s)return null;if(s.status==='closed')return{closed:true,s};
  const [{data:counts},{data:srow},{data:people}]=await Promise.all([
    sb.rpc('v2_public_live_counts',{p_code:code}),
    sb.from('v2_sessions').select('id,current_question_id,status,competitive,team_mode').eq('id',s.session_id).maybeSingle(),
    sb.rpc('v2_public_session_people',{p_code:code})
  ]);
  if(!srow||srow.status==='closed')return{closed:true,s:{...s,...srow}};
  let q=null;if(srow.current_question_id)q=(await sb.from('v2_questions').select('*').eq('id',srow.current_question_id).maybeSingle()).data;
  let ranking=[];if(s.competitive)ranking=(await sb.rpc('v2_public_ranking',{p_code:code})).data||[];
  return{s:{...s,...srow},counts:counts?.[0]||{participant_count:0,answered_count:0},q,people:people||[],ranking};
}

function remaining(q){if(!q?.launched_at||q.status!=='live')return 0;return Math.max(0,Math.ceil(Number(q.timer_seconds||30)-(Date.now()-new Date(q.launched_at).getTime())/1000))}
function hotspotMedia(q){const c=q.status==='revealed'?q.correct_answer:null;return `<div style="position:relative;display:inline-block;max-width:100%;width:100%"><img class="pj-media" style="display:block;width:100%;margin:0" src="${esc(q.media_url)}" alt="Recurso visual">${c?.x!=null&&c?.y!=null?`<span title="Zona correcta" style="position:absolute;left:${Number(c.x)}%;top:${Number(c.y)}%;width:48px;height:48px;transform:translate(-50%,-50%);border:5px solid #22c55e;border-radius:999px;box-shadow:0 0 0 7px rgba(34,197,94,.2);pointer-events:none"></span>`:''}</div>`}
function media(q){if(!q?.media_url)return'';if(q.question_type==='hotspot'&&q.media_type==='image')return hotspotMedia(q);if(q.media_type==='image')return`<img class="pj-media" src="${esc(q.media_url)}" alt="Recurso de la pregunta">`;if(q.media_type==='audio')return`<audio controls style="width:100%" src="${esc(q.media_url)}"></audio>`;if(q.media_type==='video')return`<video controls class="pj-media" src="${esc(q.media_url)}"></video>`;return''}
function correctSet(q){if(q.status!=='revealed')return new Set();const a=q.correct_answer;return new Set((Array.isArray(a)?a:[a]).filter(x=>x!=null).map(String))}
function options(q){if(q.question_type==='open_text')return'<div class="pj-option">Respuesta abierta</div>';if(q.question_type==='numeric')return q.status==='revealed'?`<div class="pj-option correct">Respuesta: ${esc(q.correct_answer)}</div>`:'<div class="pj-option">Respuesta numérica</div>';if(q.question_type==='hotspot')return q.status==='revealed'?'<div class="pj-option correct">La zona correcta está marcada en verde.</div>':'<div class="pj-option">Selecciona la zona correcta en la imagen.</div>';if(q.question_type==='ordering'&&q.status==='revealed'&&Array.isArray(q.correct_answer))return`<ol style="font-size:clamp(20px,2vw,32px);line-height:1.45">${q.correct_answer.map(x=>`<li>${esc(x)}</li>`).join('')}</ol>`;const opts=Array.isArray(q.options)?q.options:[],good=correctSet(q);return opts.map((o,i)=>`<div class="pj-option ${good.has(String(o))?'correct':''}">${String.fromCharCode(65+i)} · ${esc(o)}</div>`).join('')}
function rankingHtml(rows,teamMode){let arr=rows;if(teamMode){const map=new Map();rows.forEach(r=>{const k=r.team||'Sin equipo',x=map.get(k)||{name:k,points:0,correct:0,answered:0};x.points+=Number(r.points||0);x.correct+=Number(r.correct||0);x.answered+=Number(r.answered||0);map.set(k,x)});arr=[...map.values()].sort((a,b)=>b.points-a.points)}return `<div class="pj-ranking"><h2>🏆 ${teamMode?'Equipos':'Ranking'}</h2>${arr.length?`<div class="pj-podium">${arr.slice(0,3).map((r,i)=>`<div><span>${['🥇','🥈','🥉'][i]}</span><b>${esc(r.name)}</b><div>${r.points} pts</div></div>`).join('')}</div>${arr.map((r,i)=>`<div class="pj-rank"><div class="pj-pos">${i+1}</div><div><b>${esc(r.name)}</b><div>${r.correct||0} correctas</div></div><strong>${r.points||0}</strong></div>`).join('')}`:'<p>Aún no hay puntuación.</p>'}</div>`}

function closed(x){clearInterval(timer);currentScreen='closed';root.innerHTML=`<div class="pj-entry"><div class="pj-card">${logo()}<span class="pj-chip">Sesión finalizada</span><h1>${esc(x.s?.title||'TEDVIO')}</h1><p>${esc(x.s?.university||'')}${x.s?.educational_program?' · '+esc(x.s.educational_program):''}${x.s?.group_name?' · '+esc(x.s.group_name):''}</p><button id="pjAnother">Abrir otra sesión</button></div></div>`;document.querySelector('#pjAnother').onclick=()=>{code='';history.replaceState(null,'','./proyectar.html');entry()}}

function drawQR(){const el=document.querySelector('#pjQR');if(el&&typeof QRCode!=='undefined'&&!el.dataset.ready){el.dataset.ready='1';new QRCode(el,{text:`${location.origin}/beta.html#join?code=${code}`,width:220,height:220,correctLevel:QRCode.CorrectLevel.M})}}
function renderWaiting(x){currentScreen=`waiting:${x.s.session_id}`;root.innerHTML=`<div class="pj"><div class="pj-top">${logo()}<span class="pj-chip">Sala de espera</span></div><div class="pj-wait"><section><div class="pj-sub">${esc(x.s.university||'')}</div><h1 class="pj-title">${esc(x.s.title||'TEDVIO')}</h1><p class="pj-sub">${esc(x.s.educational_program||'')}${x.s.group_name?' · '+esc(x.s.group_name):''}</p><div class="pj-code">${esc(code)}</div><p class="pj-sub">Escanea el QR o entra a TEDVIO con este código.</p></section><section class="pj-card"><div id="pjQR" class="pj-qr"></div><h2 id="pjConnectedCount">0 conectados</h2><div class="pj-joiners" id="pjJoiners"></div></section></div></div>`;drawQR();lastPeople=new Set();lastPeopleKey='';updateWaiting(x)}
function updateWaiting(x){const names=x.people.map(p=>p.display_name),key=names.join('|');const count=document.querySelector('#pjConnectedCount');if(count)count.textContent=`${names.length} conectados`;if(key===lastPeopleKey)return;const newOnes=new Set(names.filter(n=>!lastPeople.has(n)));lastPeople=new Set(names);lastPeopleKey=key;const box=document.querySelector('#pjJoiners');if(box){box.innerHTML=names.map(n=>`<span class="pj-person ${newOnes.has(n)?'new':''}">${esc(n)}</span>`).join('')||'<span>Esperando alumnos…</span>';if(newOnes.size)setTimeout(()=>box.querySelectorAll('.new').forEach(e=>e.classList.remove('new')),1400)}}

function liveScreenKey(x){const q=x.q;return `live:${q.id}:${q.status}:${q.media_url||''}:${JSON.stringify(q.options||[])}:${JSON.stringify(q.correct_answer||null)}`}
function renderLive(x){const q=x.q,showRank=q.status!=='live'&&x.s.competitive;currentScreen=liveScreenKey(x);lastRankKey='';root.innerHTML=`<div class="pj"><div class="pj-top">${logo()}<span class="pj-chip">Código ${esc(code)}</span></div><div class="pj-live"><section class="pj-question"><div><span style="font-weight:900;color:#2468ff">Pregunta ${q.position} · ${esc(typeLabel[q.question_type]||q.question_type)}</span><h1>${esc(q.prompt)}</h1></div>${media(q)}<div class="pj-options">${options(q)}</div>${q.status==='revealed'&&q.explanation?`<div class="pj-explain"><b>💡 Explicación</b><div>${esc(q.explanation)}</div></div>`:''}</section><aside class="pj-side"><div class="pj-metric"><span>Tiempo</span><b class="pj-timer">${q.status==='live'?remaining(q)+' s':'—'}</b></div><div class="pj-metric"><span>Respuestas</span><b id="pjAnswerCount">${x.counts.answered_count||0}/${x.counts.participant_count||0}</b></div><div id="pjSideDynamic">${showRank?rankingHtml(x.ranking,x.s.team_mode):`<div class="pj-metric"><span>${q.status==='live'?'Respondiendo…':'Resultados'}</span><b>${q.status==='revealed'?'✓':'—'}</b></div>`}</div></aside></div></div>`;updateLive(x)}
function updateLive(x){const q=x.q,t=document.querySelector('.pj-timer'),a=document.querySelector('#pjAnswerCount');if(t)t.textContent=q.status==='live'?remaining(q)+' s':'—';if(a)a.textContent=`${x.counts.answered_count||0}/${x.counts.participant_count||0}`;if(q.status!=='live'&&x.s.competitive){const key=JSON.stringify(x.ranking||[])+String(x.s.team_mode);if(key!==lastRankKey){lastRankKey=key;const d=document.querySelector('#pjSideDynamic');if(d)d.innerHTML=rankingHtml(x.ranking,x.s.team_mode)}}}

async function paint(){if(busy)return;busy=true;try{const x=await fetchState();if(!x){if(currentScreen!=='missing'){currentScreen='missing';root.innerHTML='<div class="pj-entry"><div class="pj-card"><h1>Código no encontrado</h1><button id="pjRetry">Cambiar código</button></div></div>';document.querySelector('#pjRetry').onclick=()=>{code='';history.replaceState(null,'','./proyectar.html');entry()}}return}lastGood=x;if(x.closed)return closed(x);if(!x.q){const key=`waiting:${x.s.session_id}`;if(currentScreen!==key)renderWaiting(x);else updateWaiting(x)}else{const key=liveScreenKey(x);if(currentScreen!==key)renderLive(x);else updateLive(x)}}catch(e){console.error('TEDVIO projection',e);if(!lastGood&&currentScreen!=='reconnecting'){currentScreen='reconnecting';root.innerHTML=`<div class="pj-entry"><div class="pj-card">${logo()}<h1>Reconectando…</h1><p>La proyección intentará recuperar la sesión automáticamente.</p></div></div>`}}finally{busy=false}}
function start(){clearInterval(timer);currentScreen='';paint();timer=setInterval(paint,850)}
window.addEventListener('online',paint);code.length===6?start():entry();