import {createClient} from 'https://esm.sh/@supabase/supabase-js@2';
const cfg=window.TEDVIO_CONFIG||{},sb=createClient(cfg.SUPABASE_URL,cfg.SUPABASE_PUBLISHABLE_KEY),root=document.querySelector('#projectionApp');
const esc=(v='')=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
let code=new URLSearchParams(location.search).get('code')||'',lastPeople=new Set(),timer=null;
function logo(){return '<img class="pj-logo" src="./assets/tedvio_logo_horizontal_650.png" alt="TEDVIO">'}
function entry(){root.innerHTML=`<div class="pj-entry"><div class="pj-card">${logo()}<h1>Pantalla de proyección</h1><p>Escribe el código de la sesión.</p><input id="pjCode" inputmode="numeric" maxlength="6" value="${esc(code)}"><button id="pjGo">Abrir proyección</button></div></div>`;document.querySelector('#pjGo').onclick=()=>{code=document.querySelector('#pjCode').value.trim();if(code.length!==6)return;history.replaceState(null,'',`?code=${code}`);start()}}
async function fetchState(){const [{data:meta},{data:counts}]=await Promise.all([sb.rpc('v2_public_session_meta',{p_code:code}),sb.rpc('v2_public_live_counts',{p_code:code})]);const s=meta?.[0],c=counts?.[0];if(!s)return null;const {data:srow}=await sb.from('v2_sessions').select('id,current_question_id,status,competitive,team_mode').eq('id',s.session_id).maybeSingle();let q=null;if(srow?.current_question_id)q=(await sb.from('v2_questions').select('*').eq('id',srow.current_question_id).maybeSingle()).data;const {data:people}=await sb.from('v2_participants').select('display_name,team_name').eq('session_id',s.session_id).order('joined_at');let ranking=[];if(s.competitive)ranking=(await sb.rpc('v2_public_ranking',{p_code:code})).data||[];return{s:{...s,...srow},counts:c||{participant_count:0,answered_count:0},q,people:people||[],ranking}}
function remaining(q){if(!q?.launched_at||q.status!=='live')return 0;return Math.max(0,Math.ceil(Number(q.timer_seconds||30)-(Date.now()-new Date(q.launched_at).getTime())/1000))}
function media(q){if(!q?.media_url)return'';if(q.media_type==='image')return`<img class="pj-media" src="${esc(q.media_url)}">`;if(q.media_type==='audio')return`<audio controls style="width:100%" src="${esc(q.media_url)}"></audio>`;if(q.media_type==='video')return`<video controls class="pj-media" src="${esc(q.media_url)}"></video>`;return''}
function correctSet(q){if(q.status!=='revealed')return new Set();const a=q.correct_answer;return new Set(Array.isArray(a)?a:[a].filter(x=>x!=null).map(String))}
function options(q){if(q.question_type==='open_text')return'<div class="pj-option">Respuesta abierta</div>';if(q.question_type==='numeric')return q.status==='revealed'?`<div class="pj-option correct">Respuesta: ${esc(q.correct_answer)}</div>`:'<div class="pj-option">Respuesta numérica</div>';if(q.question_type==='hotspot')return'<div class="pj-option">Selecciona la zona correcta en la imagen</div>';const opts=Array.isArray(q.options)?q.options:[],good=correctSet(q);return opts.map((o,i)=>`<div class="pj-option ${good.has(String(o))?'correct':''}">${String.fromCharCode(65+i)} · ${esc(o)}</div>`).join('')}
function rankingHtml(rows,teamMode){let arr=rows;if(teamMode){const map=new Map();rows.forEach(r=>{const k=r.team||'Sin equipo',x=map.get(k)||{name:k,points:0,correct:0,answered:0};x.points+=Number(r.points||0);x.correct+=Number(r.correct||0);x.answered+=Number(r.answered||0);map.set(k,x)});arr=[...map.values()].sort((a,b)=>b.points-a.points)}return `<div class="pj-ranking"><h2>🏆 ${teamMode?'Equipos':'Ranking'}</h2>${arr.length?`<div class="pj-podium">${arr.slice(0,3).map((r,i)=>`<div><span>${['🥇','🥈','🥉'][i]}</span><b>${esc(r.name)}</b><div>${r.points} pts</div></div>`).join('')}</div>${arr.map((r,i)=>`<div class="pj-rank"><div class="pj-pos">${i+1}</div><div><b>${esc(r.name)}</b><div>${r.correct||0} correctas</div></div><strong>${r.points||0}</strong></div>`).join('')}`:'<p>Aún no hay puntuación.</p>'}</div>`}
function waiting(x){const names=x.people.map(p=>p.display_name),newOnes=new Set(names.filter(n=>!lastPeople.has(n)));lastPeople=new Set(names);root.innerHTML=`<div class="pj"><div class="pj-top">${logo()}<span class="pj-chip">Sala de espera</span></div><div class="pj-wait"><section><div class="pj-sub">${esc(x.s.university||'')}</div><h1 class="pj-title">${esc(x.s.title||'TEDVIO')}</h1><p class="pj-sub">${esc(x.s.educational_program||'')}${x.s.group_name?' · '+esc(x.s.group_name):''}</p><div class="pj-code">${esc(code)}</div><p class="pj-sub">Escanea el QR o entra a TEDVIO con este código.</p></section><section class="pj-card"><div id="pjQR" class="pj-qr"></div><h2>${names.length} conectados</h2><div class="pj-joiners">${names.map(n=>`<span class="pj-person ${newOnes.has(n)?'new':''}">${esc(n)}</span>`).join('')||'<span>Esperando alumnos…</span>'}</div></section></div></div>`;setTimeout(()=>{const el=document.querySelector('#pjQR');if(el&&typeof QRCode!=='undefined')new QRCode(el,{text:`${location.origin}/beta.html#join?code=${code}`,width:220,height:220,correctLevel:QRCode.CorrectLevel.M})},20)}
function live(x){const q=x.q,showRank=q.status!=='live'&&x.s.competitive;root.innerHTML=`<div class="pj"><div class="pj-top">${logo()}<span class="pj-chip">Código ${esc(code)}</span></div><div class="pj-live"><section class="pj-question"><div><span style="font-weight:900;color:#2468ff">Pregunta ${q.position} · ${esc(q.question_type)}</span><h1>${esc(q.prompt)}</h1></div>${media(q)}<div class="pj-options">${options(q)}</div>${q.status==='revealed'&&q.explanation?`<div class="pj-explain"><b>💡 Explicación</b><div>${esc(q.explanation)}</div></div>`:''}</section><aside class="pj-side"><div class="pj-metric"><span>Tiempo</span><b class="pj-timer">${q.status==='live'?remaining(q)+' s':'—'}</b></div><div class="pj-metric"><span>Respuestas</span><b>${x.counts.answered_count||0}/${x.counts.participant_count||0}</b></div>${showRank?rankingHtml(x.ranking,x.s.team_mode):`<div class="pj-metric"><span>${q.status==='live'?'Respondiendo…':'Resultados'}</span><b>${q.status==='revealed'?'✓':'—'}</b></div>`}</aside></div></div>`}
async function paint(){try{const x=await fetchState();if(!x){root.innerHTML='<div class="pj-entry"><div class="pj-card"><h1>Código no encontrado</h1><button onclick="location.href=\'./proyectar.html\'">Cambiar código</button></div></div>';return}if(!x.q)waiting(x);else live(x)}catch(e){console.error(e)}}
function start(){clearInterval(timer);paint();timer=setInterval(paint,1000)}
code.length===6?start():entry();
