import{createClient}from'https://esm.sh/@supabase/supabase-js@2';
const cfg=window.TEDVIO_CONFIG||{},sb=createClient(cfg.SUPABASE_URL,cfg.SUPABASE_PUBLISHABLE_KEY);
const root=document.querySelector('#betaApp');
const VERSION='2026.08.25.60',STUDENT_KEY='tedvio_v2_student';
const typeLabel={multiple_choice:'Opción múltiple',multiple_select:'Selección múltiple',true_false:'Verdadero / Falso',open_text:'Respuesta abierta',numeric:'Numérica',poll:'Encuesta',scale_5:'Escala 1–5',ordering:'Ordenar',hotspot:'Zona de imagen'};
const graded=new Set(['multiple_choice','multiple_select','true_false','numeric','ordering','hotspot']);
const esc=(v='')=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const nativeSet=window.__TEDVIO_NATIVE_SET_INTERVAL__||window.setInterval.bind(window),nativeClear=window.__TEDVIO_NATIVE_CLEAR_INTERVAL__||window.clearInterval.bind(window);
const S={student:null,session:null,questions:[],question:null,answers:{},resultRows:[],answerFeedback:null,rankFeedback:null,correctAnswer:null,busy:false,submitBusy:false,poll:null,timer:null,renderKey:'',multi:new Set(),order:[],hotspot:null,lastQuestion:null,reconnecting:false};
const onStudent=()=>location.hash.startsWith('#student');
const answerKey=()=>S.student?.participantId?`tedvio.v60.answers.${S.student.participantId}`:'';
function readStudent(){try{return JSON.parse(localStorage.getItem(STUDENT_KEY)||'null')}catch{return null}}
function readAnswers(){try{return JSON.parse(localStorage.getItem(answerKey())||'{}')||{}}catch{return{}}}
function saveAnswers(){if(answerKey())localStorage.setItem(answerKey(),JSON.stringify(S.answers))}
function stopLegacy(){const id=window.__TEDVIO_STUDENT_INTERVAL__;if(id){try{nativeClear(id)}catch{}window.__TEDVIO_STUDENT_INTERVAL__=null}document.documentElement.dataset.tvStudentV60='1'}
function cleanup(){document.documentElement.removeAttribute('data-tv-student-v60');document.body.classList.remove('tv60-student-page');S.renderKey='';S.session=null;S.questions=[];S.question=null;S.resultRows=[];S.answerFeedback=null;S.rankFeedback=null;S.correctAnswer=null;S.multi.clear();S.order=[];S.hotspot=null}
function logo(){return'<img class="tv60-logo" src="./assets/tedvio_official_horizontal.svg?v=60" alt="TEDVIO">'}
function friendly(e){const m=String(e?.message||e||'No se pudo completar la operación.');if(m.includes('duplicate'))return'Esta respuesta ya estaba registrada.';if(m.includes('QUESTION_EXPIRED'))return'El tiempo de esta pregunta terminó.';if(m.includes('QUESTION_NOT_LIVE'))return'Esta pregunta ya no acepta respuestas.';return m}
function remaining(q){if(!q?.launched_at||q.status!=='live')return 0;return Math.max(0,Math.ceil(Number(q.timer_seconds||30)-(Date.now()-new Date(q.launched_at).getTime())/1000))}
function summary(){const rows=Object.values(S.answers||{});return{answered:rows.length,correct:rows.filter(x=>x.is_correct===true).length,points:rows.reduce((a,x)=>a+Number(x.points||0),0),streak:rows.reduce((a,x)=>Math.max(a,Number(x.streak||0)),0)}}
function answerFor(q){return q?S.answers[q.id]||null:null}
function resetInteraction(qid){if(S.lastQuestion===qid)return;S.lastQuestion=qid;S.multi.clear();S.order=[];S.hotspot=null;S.resultRows=[];S.answerFeedback=null;S.rankFeedback=null;S.correctAnswer=null}
async function fetchState(){if(!onStudent()||S.busy)return;S.busy=true;try{stopLegacy();S.student=readStudent();if(!S.student){location.hash='#join';return}if(!Object.keys(S.answers).length)S.answers=readAnswers();const {data:s,error:se}=await sb.from('v2_sessions').select('id,code,title,status,current_question_id,competitive,team_mode,started_at,closed_at').eq('id',S.student.sessionId).maybeSingle();if(se)throw se;if(!s){showGone();return}S.session=s;const {data:qs,error:qe}=await sb.from('v2_questions').select('id,position,prompt,question_type,options,media_url,media_type,timer_seconds,status,launched_at,closed_at').eq('session_id',s.id).order('position');if(qe)throw qe;S.questions=qs||[];S.question=S.questions.find(x=>x.id===s.current_question_id)||null;resetInteraction(S.question?.id||null);if(s.status==='closed'){await fetchRank();paint();return}if(S.question?.status==='revealed')await fetchReveal(S.question);else{S.resultRows=[];S.answerFeedback=null;S.rankFeedback=null;S.correctAnswer=null}S.reconnecting=false;paint()}catch(e){console.error('TEDVIO Student v60',e);S.reconnecting=true;paint();log('student60_sync_error',{message:String(e?.message||e)})}finally{S.busy=false}}
async function fetchReveal(q){const tasks=[sb.rpc('v2_public_question_results',{p_session_id:S.session.id,p_question_id:q.id}),sb.rpc('v2_student_answer_feedback',{p_question_id:q.id,p_participant_id:S.student.participantId}),sb.rpc('v2_student_feedback',{p_session_id:S.session.id,p_participant_id:S.student.participantId}),sb.from('v2_questions').select('correct_answer').eq('id',q.id).maybeSingle()];const[r,f,rank,c]=await Promise.all(tasks);S.resultRows=r.data||[];S.answerFeedback=f.data?.[0]||null;S.rankFeedback=rank.data?.[0]||null;S.correctAnswer=c.data?.correct_answer??null}
async function fetchRank(){try{const{data}=await sb.rpc('v2_student_feedback',{p_session_id:S.student.sessionId,p_participant_id:S.student.participantId});S.rankFeedback=data?.[0]||null}catch{}}
function top(){const pct=S.question?Math.max(0,Math.min(100,remaining(S.question)/Math.max(1,Number(S.question.timer_seconds||30))*100)):0;return`<header class="tv60-top">${logo()}<div class="tv60-top-right"><span class="tv60-net ${navigator.onLine&&!S.reconnecting?'ok':'bad'}">${navigator.onLine&&!S.reconnecting?'Conectado':'Reconectando'}</span>${S.session?.code?`<span class="tv60-code">${esc(S.session.code)}</span>`:''}</div></header>${S.question?`<div class="tv60-progress-head"><span>Pregunta ${S.question.position} de ${Math.max(S.questions.length,S.question.position||1)}</span><span id="tv60TimeLabel">${S.question.status==='live'?remaining(S.question)+' s':S.question.status==='revealed'?'Resultado':'Cerrada'}</span><i><b id="tv60TimeBar" style="width:${S.question.status==='live'?pct:100}%"></b></i></div>`:''}`}
function shell(body){document.body.classList.add('tv60-student-page');root.innerHTML=`<div class="tv60-app">${top()}<main class="tv60-main">${S.reconnecting?'<div class="tv60-offline">La conexión se interrumpió. TEDVIO está intentando recuperar tu sesión automáticamente.</div>':''}${body}</main></div>`}
function showGone(){shell(`<section class="tv60-state"><div class="tv60-state-icon">?</div><h1>No encontramos esta sesión</h1><p>Puede haber finalizado o el acceso ya no está disponible.</p><button class="tv60-btn primary" onclick="tv60Leave()">Entrar a otra sesión</button></section>`)}
function waitingHtml(){const sum=summary(),team=S.student?.team?` · ${esc(S.student.team)}`:'';return`<section class="tv60-wait"><div class="tv60-pulse"><i></i></div><span class="tv60-kicker">Sesión activa</span><h1>Estás dentro.</h1><p>Espera a que tu profesor lance la siguiente pregunta.</p><div class="tv60-identity"><b>${esc(S.student?.name||'Alumno')}</b><span>${esc(S.session?.title||'TEDVIO')}${team}</span></div><div class="tv60-mini-grid"><div><span>Respuestas enviadas</span><b>${sum.answered}</b></div><div><span>Código</span><b>${esc(S.session?.code||'—')}</b></div></div></section>`}
function media(q){if(!q?.media_url||q.question_type==='hotspot')return'';if(q.media_type==='image')return`<img class="tv60-media" src="${esc(q.media_url)}" alt="Recurso de la pregunta">`;if(q.media_type==='audio')return`<audio class="tv60-audio" controls src="${esc(q.media_url)}"></audio>`;if(q.media_type==='video')return`<video class="tv60-media" controls src="${esc(q.media_url)}"></video>`;return''}
function optionButtons(q){const opts=Array.isArray(q.options)?q.options:[];if(['multiple_choice','true_false','poll'].includes(q.question_type))return`<div class="tv60-options">${opts.map((o,i)=>`<button class="tv60-option" data-v60-one="${i}"><span>${String.fromCharCode(65+i)}</span><b>${esc(o)}</b></button>`).join('')}</div>`;if(q.question_type==='multiple_select')return`<div class="tv60-options">${opts.map((o,i)=>`<button class="tv60-option ${S.multi.has(String(i))?'selected':''}" data-v60-multi="${i}"><span>${S.multi.has(String(i))?'✓':String.fromCharCode(65+i)}</span><b>${esc(o)}</b></button>`).join('')}</div><button class="tv60-btn primary wide" id="tv60SubmitMulti" ${S.multi.size?'':'disabled'}>Enviar selección</button>`;if(q.question_type==='scale_5')return`<div class="tv60-scale">${['1','2','3','4','5'].map(x=>`<button data-v60-scale="${x}">${x}</button>`).join('')}</div>`;if(q.question_type==='open_text')return`<textarea id="tv60Open" class="tv60-input" rows="6" maxlength="1200" placeholder="Escribe tu respuesta"></textarea><button class="tv60-btn primary wide" id="tv60SubmitOpen">Enviar respuesta</button>`;if(q.question_type==='numeric')return`<input id="tv60Num" class="tv60-input" type="number" step="any" inputmode="decimal" placeholder="Escribe tu respuesta"><button class="tv60-btn primary wide" id="tv60SubmitNum">Enviar respuesta</button>`;if(q.question_type==='ordering'){const left=opts.map((o,i)=>({o,i})).filter(x=>!S.order.includes(x.i));return`<p class="tv60-hint">Toca los elementos en el orden correcto.</p><div class="tv60-order-picked">${S.order.length?S.order.map((i,n)=>`<button data-v60-order-remove="${n}"><span>${n+1}</span>${esc(opts[i])}</button>`).join(''):'<div>Selecciona el primer elemento</div>'}</div><div class="tv60-options compact">${left.map(x=>`<button class="tv60-option" data-v60-order="${x.i}"><span>＋</span><b>${esc(x.o)}</b></button>`).join('')}</div><button class="tv60-btn primary wide" id="tv60SubmitOrder" ${S.order.length===opts.length?'':'disabled'}>Enviar orden</button>`}if(q.question_type==='hotspot')return hotspotHtml(q);return'<div class="tv60-closed">Tipo de pregunta no disponible en este dispositivo.</div>'}
function hotspotHtml(q){if(!q.media_url)return'<div class="tv60-closed">Esta pregunta necesita una imagen.</div>';const mark=S.hotspot?`<i class="tv60-hot-mark" style="left:${S.hotspot.x}%;top:${S.hotspot.y}%"></i>`:'';return`<p class="tv60-hint">Toca la zona que consideres correcta.</p><div class="tv60-hot" id="tv60Hot"><img src="${esc(q.media_url)}" alt="Imagen de la pregunta">${mark}</div><button class="tv60-btn primary wide" id="tv60SubmitHot" ${S.hotspot?'':'disabled'}>Enviar ubicación</button>`}
function liveQuestionHtml(q){const rem=remaining(q);if(q.status!=='live'||rem<=0)return missedHtml(q);return`<section class="tv60-question"><div class="tv60-chips"><span>${esc(typeLabel[q.question_type]||q.question_type)}</span><span class="live">Respondiendo</span></div><h1>${esc(q.prompt)}</h1>${media(q)}<div class="tv60-answer-area">${optionButtons(q)}</div><p class="tv60-secure">Tu respuesta se registra una sola vez.</p></section>`}
function submittedHtml(q){return`<section class="tv60-state submitted"><div class="tv60-state-icon">✓</div><span class="tv60-kicker">Respuesta registrada</span><h1>Listo.</h1><p>Tu respuesta quedó guardada. Espera a que el profesor muestre el resultado.</p><div class="tv60-wait-line"><i></i><span>${q.status==='live'?'La pregunta sigue abierta':'Esperando resultado'}</span></div></section>`}
function missedHtml(q){return`<section class="tv60-state"><div class="tv60-state-icon muted">⌛</div><span class="tv60-kicker">Respuestas cerradas</span><h1>Espera el resultado.</h1><p>${answerFor(q)?'Tu respuesta ya está registrada.':'No se registró una respuesta en esta pregunta.'}</p></section>`}
function resultStats(){const f=S.rankFeedback||{};return S.session?.competitive?`<div class="tv60-result-stats"><div><span>Puntos</span><b>${answerFor(S.question)?.points??'—'}</b></div><div><span>Posición</span><b>${f.rank?`#${f.rank}`:'—'}</b></div>${S.session.team_mode?`<div><span>Equipo</span><b>${f.team_rank?`#${f.team_rank}`:'—'}</b></div>`:''}</div>`:''}
function formatCorrect(a){if(a==null)return'';if(Array.isArray(a))return a.map(esc).join(' · ');if(typeof a==='object'&&a.x!=null)return'Zona marcada en la imagen';return esc(a)}
function distribution(q){if(q.question_type==='open_text')return`<div class="tv60-group-note">${Number(S.resultRows?.[0]?.total||S.resultRows.length||0)} respuestas abiertas registradas en el grupo.</div>`;if(q.question_type==='hotspot')return hotspotResult(q);if(q.question_type==='ordering'&&Array.isArray(S.correctAnswer))return`<div class="tv60-correct-order">${S.correctAnswer.map((x,i)=>`<div><span>${i+1}</span>${esc(x)}</div>`).join('')}</div>`;const counts=new Map((S.resultRows||[]).map(r=>[String(r.answer),Number(r.votes||0)]));const opts=q.question_type==='scale_5'?['1','2','3','4','5']:(Array.isArray(q.options)?q.options.map(String):[...counts.keys()]);const total=Number(S.resultRows?.[0]?.total||[...counts.values()].reduce((a,b)=>a+b,0));return`<div class="tv60-bars">${opts.map((o,i)=>{const n=counts.get(String(o))||0,p=total?Math.round(n/total*100):0;return`<div><p><span>${String.fromCharCode(65+i)} · ${esc(o)}</span><b>${p}%</b></p><i><b style="width:${p}%"></b></i></div>`}).join('')}</div>`}
function hotspotResult(q){const c=S.correctAnswer,a=answerFor(q)?.answer;return`<div class="tv60-hot result"><img src="${esc(q.media_url||'')}" alt="Resultado">${c?.x!=null?`<i class="tv60-hot-correct" style="left:${Number(c.x)}%;top:${Number(c.y)}%"></i>`:''}${a?.x!=null?`<i class="tv60-hot-mine" style="left:${Number(a.x)}%;top:${Number(a.y)}%"></i>`:''}</div><div class="tv60-hot-legend"><span><i class="correct"></i>Zona correcta</span><span><i class="mine"></i>Tu selección</span></div>`}
function revealHtml(q){const own=answerFor(q),isGraded=graded.has(q.question_type),known=own&&typeof own.is_correct==='boolean';const title=!own?'No respondiste esta pregunta':!isGraded?'Respuesta registrada':known?(own.is_correct?'¡Correcto!':'Esta vez no fue correcta'):'Respuesta registrada';const cls=known&&isGraded?(own.is_correct?'good':'bad'):'neutral';return`<section class="tv60-result"><div class="tv60-personal ${cls}"><div class="tv60-result-icon">${!own?'—':!isGraded?'✓':known?(own.is_correct?'✓':'×'):'✓'}</div><span class="tv60-kicker">Tu resultado</span><h1>${title}</h1>${resultStats()}</div>${S.correctAnswer!=null?`<div class="tv60-correct"><span>Respuesta correcta</span><b>${formatCorrect(S.correctAnswer)}</b></div>`:''}<div class="tv60-group"><h2>Así respondió el grupo</h2>${distribution(q)}</div>${S.answerFeedback?.explanation?`<div class="tv60-explain"><b>💡 Explicación</b><p>${esc(S.answerFeedback.explanation)}</p></div>`:''}<div class="tv60-next"><i></i><span>Espera la siguiente pregunta</span></div></section>`}
function closedHtml(){const sum=summary(),f=S.rankFeedback||{};return`<section class="tv60-finish"><div class="tv60-finish-mark">✓</div><span class="tv60-kicker">Sesión finalizada</span><h1>Buen trabajo, ${esc(S.student?.name||'')}.</h1><p>${esc(S.session?.title||'TEDVIO')} terminó.</p><div class="tv60-final-grid"><div><span>Respondidas</span><b>${sum.answered}</b></div><div><span>Correctas</span><b>${sum.correct}</b></div>${S.session?.competitive?`<div><span>Puntos</span><b>${sum.points}</b></div><div><span>Posición</span><b>${f.rank?`#${f.rank}`:'—'}</b></div>`:''}</div><button class="tv60-btn primary wide" onclick="tv60Leave()">Entrar a otra sesión</button></section>`}
function key(){return[S.session?.id,S.session?.status,S.question?.id,S.question?.status,!!answerFor(S.question),S.questions.length,S.resultRows.length,S.reconnecting,navigator.onLine].join('|')}
function paint(){if(!onStudent()||!S.session)return;const k=key();if(k===S.renderKey){tick();return}S.renderKey=k;if(S.session.status==='closed')return shell(closedHtml());if(!S.question)return shell(waitingHtml());const own=answerFor(S.question);if(S.question.status==='revealed')return shell(revealHtml(S.question));if(own)return shell(submittedHtml(S.question));return shell(liveQuestionHtml(S.question))}
function bind(){const q=S.question;if(!q||q.status!=='live'||answerFor(q))return;document.querySelectorAll('[data-v60-one]').forEach(b=>b.onclick=()=>submit(q,q.options[Number(b.dataset.v60One)]));document.querySelectorAll('[data-v60-scale]').forEach(b=>b.onclick=()=>submit(q,b.dataset.v60Scale));document.querySelectorAll('[data-v60-multi]').forEach(b=>b.onclick=()=>{const k=b.dataset.v60Multi;S.multi.has(k)?S.multi.delete(k):S.multi.add(k);S.renderKey='';paint();setTimeout(bind,0)});document.querySelector('#tv60SubmitMulti')?.addEventListener('click',()=>submit(q,[...S.multi].map(i=>q.options[Number(i)]).sort()));document.querySelector('#tv60SubmitOpen')?.addEventListener('click',()=>{const v=document.querySelector('#tv60Open')?.value.trim();if(!v)return flash('Escribe una respuesta.');submit(q,v)});document.querySelector('#tv60SubmitNum')?.addEventListener('click',()=>{const v=document.querySelector('#tv60Num')?.value;if(v===''||v==null)return flash('Escribe un número.');submit(q,Number(v))});document.querySelectorAll('[data-v60-order]').forEach(b=>b.onclick=()=>{S.order.push(Number(b.dataset.v60Order));S.renderKey='';paint();setTimeout(bind,0)});document.querySelectorAll('[data-v60-order-remove]').forEach(b=>b.onclick=()=>{S.order.splice(Number(b.dataset.v60OrderRemove),1);S.renderKey='';paint();setTimeout(bind,0)});document.querySelector('#tv60SubmitOrder')?.addEventListener('click',()=>submit(q,S.order.map(i=>q.options[i])));const hot=document.querySelector('#tv60Hot');if(hot)hot.onclick=e=>{const img=hot.querySelector('img'),r=img.getBoundingClientRect();S.hotspot={x:Number(((e.clientX-r.left)/r.width*100).toFixed(2)),y:Number(((e.clientY-r.top)/r.height*100).toFixed(2))};S.renderKey='';paint();setTimeout(bind,0)};document.querySelector('#tv60SubmitHot')?.addEventListener('click',()=>submit(q,S.hotspot))}
async function submit(q,answer){if(S.submitBusy||q.status!=='live'||remaining(q)<=0)return;S.submitBusy=true;document.querySelectorAll('button').forEach(b=>b.disabled=true);try{const{data,error}=await sb.rpc('v2_submit_response',{p_question_id:q.id,p_participant_id:S.student.participantId,p_answer:answer});if(error){if(String(error.message).includes('duplicate')){S.answers[q.id]={answer,duplicate:true,submitted_at:new Date().toISOString()};saveAnswers();S.renderKey='';paint();return}throw error}const row=data?.[0]||{};S.answers[q.id]={answer,is_correct:typeof row.is_correct==='boolean'?row.is_correct:null,points:Number(row.points||0),streak:Number(row.streak||0),submitted_at:new Date().toISOString()};saveAnswers();try{navigator.vibrate?.(35)}catch{}S.renderKey='';paint()}catch(e){flash(friendly(e));S.renderKey='';paint()}finally{S.submitBusy=false;setTimeout(bind,0)}}
function tick(){if(!S.question||S.question.status!=='live')return;const t=document.querySelector('#tv60TimeLabel'),b=document.querySelector('#tv60TimeBar'),rem=remaining(S.question),max=Math.max(1,Number(S.question.timer_seconds||30));if(t)t.textContent=rem+' s';if(b)b.style.width=`${Math.max(0,Math.min(100,rem/max*100))}%`;if(rem<=0&&!answerFor(S.question)){document.querySelectorAll('.tv60-answer-area button,.tv60-answer-area input,.tv60-answer-area textarea').forEach(x=>x.disabled=true)}}
function flash(msg){let x=document.querySelector('#tv60Flash');if(!x){x=document.createElement('div');x.id='tv60Flash';x.className='tv60-flash';document.body.appendChild(x)}x.textContent=msg;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2200)}
window.tv60Leave=()=>{if(answerKey())localStorage.removeItem(answerKey());localStorage.removeItem(STUDENT_KEY);S.answers={};location.hash='#join'};
async function log(event,context={}){try{await sb.from('tedvio_client_events').insert({event_type:event,severity:'error',page:location.pathname+location.hash,app_version:VERSION,user_agent:navigator.userAgent.slice(0,500),context})}catch{}}
function start(){if(S.poll)return;S.poll=nativeSet(async()=>{if(onStudent())await fetchState()},850);S.timer=nativeSet(tick,250);fetchState()}
window.addEventListener('hashchange',()=>{if(onStudent()){stopLegacy();S.student=readStudent();S.answers={};S.renderKey='';start();fetchState()}else cleanup()});window.addEventListener('online',()=>{S.reconnecting=false;S.renderKey='';fetchState()});window.addEventListener('offline',()=>{S.reconnecting=true;S.renderKey='';paint()});document.addEventListener('visibilitychange',()=>{if(!document.hidden&&onStudent())fetchState()});
const mo=new MutationObserver(()=>{if(onStudent()){stopLegacy();if(!document.querySelector('.tv60-app')){S.renderKey='';paint();setTimeout(bind,0)}}});mo.observe(root,{childList:true,subtree:false});
if(onStudent()){stopLegacy();S.student=readStudent();S.answers=readAnswers();start()}window.__TEDVIO_STUDENT60__={version:VERSION,refresh:fetchState};
const originalPaint=paint;paint=function(){originalPaint();setTimeout(bind,0)};
