import React,{useEffect,useMemo,useRef,useState}from'https://esm.sh/react@19.2.0';
import{createRoot}from'https://esm.sh/react-dom@19.2.0/client';
import{createClient}from'https://esm.sh/@supabase/supabase-js@2.112.4';

const h=React.createElement;
const cfg=window.TEDVIO_CONFIG||{};
const sb=createClient(cfg.SUPABASE_URL,cfg.SUPABASE_PUBLISHABLE_KEY);
const typeLabel={multiple_choice:'Opción múltiple',multiple_select:'Selección múltiple',true_false:'Verdadero / Falso',open_text:'Respuesta abierta',numeric:'Numérica',poll:'Encuesta',scale_5:'Escala 1–5',ordering:'Ordenamiento',hotspot:'Zona de imagen'};

function useCode(){const initial=new URLSearchParams(location.search).get('code')||'';return useState(initial.trim())}
async function loadProjection(code){const{data:meta,error:me}=await sb.rpc('v2_public_session_meta',{p_code:code});if(me)throw me;const s=meta?.[0];if(!s)return null;const[{data:counts},{data:srow},{data:people}]=await Promise.all([sb.rpc('v2_public_live_counts',{p_code:code}),sb.from('v2_sessions').select('id,current_question_id,status,competitive,team_mode').eq('id',s.session_id).maybeSingle(),sb.rpc('v2_public_session_people',{p_code:code})]);if(!srow)return null;let q=null,ranking=[],results=[];if(srow.current_question_id){q=(await sb.from('v2_questions').select('*').eq('id',srow.current_question_id).maybeSingle()).data;if(q?.status==='revealed')results=(await sb.rpc('v2_public_question_results',{p_session_id:s.session_id,p_question_id:q.id})).data||[]}if(s.competitive)ranking=(await sb.rpc('v2_public_ranking',{p_code:code})).data||[];return{s:{...s,...srow},counts:counts?.[0]||{participant_count:0,answered_count:0},people:people||[],q,ranking,results,closed:srow.status==='closed'}}
function remaining(q){if(!q?.launched_at||q.status!=='live')return 0;return Math.max(0,Math.ceil(Number(q.timer_seconds||30)-(Date.now()-new Date(q.launched_at).getTime())/1000))}
function logo(){return h('img',{className:'p2-logo',src:'../assets/tedvio_official_horizontal.svg',alt:'TEDVIO'})}
function QR({code}){const ref=useRef(null);useEffect(()=>{if(!ref.current||!window.QRCode)return;ref.current.innerHTML='';new window.QRCode(ref.current,{text:`${location.origin}/student-v2/?code=${encodeURIComponent(code)}`,width:230,height:230,correctLevel:window.QRCode.CorrectLevel.M})},[code]);return h('div',{className:'p2-qr',ref})}
function Ranking({rows,teamMode}){let arr=rows||[];if(teamMode){const map=new Map();arr.forEach(r=>{const k=r.team||'Sin equipo',x=map.get(k)||{name:k,points:0,correct:0};x.points+=Number(r.points||0);x.correct+=Number(r.correct||0);map.set(k,x)});arr=[...map.values()].sort((a,b)=>b.points-a.points)}return h('section',{className:'p2-ranking'},h('h2',null,teamMode?'🏆 Equipos':'🏆 Ranking'),arr.length?arr.slice(0,8).map((r,i)=>h('div',{className:'p2-rank',key:`${r.name}-${i}`},h('div',{className:'pos'},i+1),h('div',null,h('b',null,r.name||'Alumno'),h('div',{className:'p2-sub',style:{fontSize:'12px'}},`${r.correct||0} correctas`)),h('strong',null,`${r.points||0} pts`))):h('p',{className:'p2-sub'},'Aún no hay puntuación.'))}
function Distribution({q,rows}){if(!q||q.status!=='revealed')return null;if(q.question_type==='open_text')return h('div',{className:'p2-explain'},`${rows?.[0]?.total||rows.length||0} respuestas abiertas registradas.`);const counts=new Map((rows||[]).map(r=>[String(r.answer),Number(r.votes||0)]));const opts=q.question_type==='scale_5'?['1','2','3','4','5']:(Array.isArray(q.options)?q.options.map(String):[...counts.keys()]);const total=Number(rows?.[0]?.total||[...counts.values()].reduce((a,b)=>a+b,0));return h('div',{className:'p2-bars'},opts.map((o,i)=>{const n=counts.get(String(o))||0,p=total?Math.round(n/total*100):0;return h('div',{className:'p2-barline',key:`bar-${i}`},h('p',null,`${String.fromCharCode(65+i)} · ${o}`),h('b',null,`${p}%`),h('div',{className:'p2-track'},h('i',{style:{width:`${p}%`}}))) }))}
function Media({q}){if(!q?.media_url)return null;if(q.media_type==='image')return h('div',{style:{position:'relative'}},h('img',{className:'p2-media',src:q.media_url,alt:'Recurso de la pregunta'}),q.question_type==='hotspot'&&q.status==='revealed'&&q.correct_answer?.x!=null?h('span',{style:{position:'absolute',left:`${Number(q.correct_answer.x)}%`,top:`${Number(q.correct_answer.y)}%`,width:'52px',height:'52px',transform:'translate(-50%,-50%)',border:'5px solid #28d17c',borderRadius:'999px',boxShadow:'0 0 0 8px rgba(40,209,124,.18)'}}):null);if(q.media_type==='video')return h('video',{className:'p2-media',controls:true,src:q.media_url});if(q.media_type==='audio')return h('audio',{controls:true,src:q.media_url,style:{width:'100%'}});return null}
function Options({q}){if(q.question_type==='open_text')return h('div',{className:'p2-option'},'Respuesta abierta');if(q.question_type==='numeric')return h('div',{className:`p2-option ${q.status==='revealed'?'correct':''}`},q.status==='revealed'?`Respuesta: ${q.correct_answer}`:'Respuesta numérica');if(q.question_type==='hotspot')return h('div',{className:`p2-option ${q.status==='revealed'?'correct':''}`},q.status==='revealed'?'La zona correcta está marcada en verde.':'Selecciona la zona correcta en la imagen.');if(q.question_type==='ordering'&&q.status==='revealed'&&Array.isArray(q.correct_answer))return h('div',{className:'p2-options'},q.correct_answer.map((o,i)=>h('div',{className:'p2-option correct',key:i},h('strong',null,i+1),o)));const good=new Set((Array.isArray(q.correct_answer)?q.correct_answer:[q.correct_answer]).filter(x=>x!=null).map(String));const opts=Array.isArray(q.options)?q.options:[];return h('div',{className:'p2-options'},opts.map((o,i)=>h('div',{className:`p2-option ${q.status==='revealed'&&good.has(String(o))?'correct':''}`,key:i},h('strong',null,String.fromCharCode(65+i)),o)))}
function Entry({code,setCode,onOpen,error}){return h('div',{className:'p2-app'},h('main',{className:'p2-main'},h('section',{className:'p2-panel p2-entry'},logo(),h('span',{className:'p2-kicker'},'Projection 2.x'),h('h1',null,'Pantalla de proyección'),h('p',null,'Escribe el código de la sesión para abrir el modo aula.'),h('input',{className:'p2-code-input',value:code,onChange:e=>setCode(e.target.value.replace(/\D/g,'').slice(0,6)),inputMode:'numeric',maxLength:6,placeholder:'000000'}),error?h('p',{style:{color:'#ff9b9b'}},error):null,h('button',{className:'p2-btn',onClick:onOpen,disabled:code.length!==6},'Abrir proyección'))))}
function Lobby({x,code}){return h('div',{className:'p2-app'},h('header',{className:'p2-top'},logo(),h('span',{className:'p2-chip'},h('span',{className:'p2-dot'}),'Sala activa')),h('main',{className:'p2-main'},h('section',{className:'p2-panel p2-lobby'},h('div',{className:'p2-lobby-primary'},h('span',{className:'p2-kicker'},x.s.university||'TEDVIO'),h('h1',null,x.s.title||'Clase en vivo'),h('p',{className:'p2-sub'},[x.s.educational_program,x.s.group_name].filter(Boolean).join(' · ')),h('div',{className:'p2-big-code'},code),h('p',{className:'p2-sub'},'Escanea el QR o entra a TEDVIO con este código.'),h('div',{className:'p2-people'},(x.people||[]).slice(0,30).map((p,i)=>h('span',{className:'p2-person',key:i},p.display_name)))),h('aside',{className:'p2-qr-card'},h(QR,{code}),h('div',{className:'p2-connected'},`${x.people.length} conectados`),h('div',{style:{marginTop:'6px',color:'#6380a8'}},'Listos para comenzar'))))) }
function Live({x,code,tick}){const q=x.q,rem=remaining(q),pct=Math.max(0,Math.min(100,rem/Math.max(1,Number(q.timer_seconds||30))*100));return h('div',{className:'p2-app'},h('header',{className:'p2-top'},logo(),h('span',{className:'p2-chip'},`Código ${code}`)),h('main',{className:'p2-main'},h('div',{className:'p2-live'},h('section',{className:'p2-panel p2-question'},h('div',null,h('span',{className:'p2-kicker'},`Pregunta ${q.position} · ${typeLabel[q.question_type]||q.question_type}`),h('h1',null,q.prompt)),h(Media,{q}),h(Options,{q}),q.status==='revealed'&&q.explanation?h('div',{className:'p2-explain'},h('b',null,'Explicación'),h('div',{style:{marginTop:'6px'}},q.explanation)):null,q.status==='revealed'?h(Distribution,{q,rows:x.results}):null),h('aside',{className:'p2-side'},h('section',{className:'p2-metric'},h('span',null,q.status==='live'?'Tiempo':'Estado'),h('b',null,q.status==='live'?`${rem} s`:'Resultado'),h('div',{className:'p2-timerbar'},h('i',{style:{width:q.status==='live'?`${pct}%`:'100%'}}))),h('section',{className:'p2-metric'},h('span',null,'Respuestas'),h('b',null,`${x.counts.answered_count||0}/${x.counts.participant_count||0}`)),x.s.competitive?h(Ranking,{rows:x.ranking,teamMode:x.s.team_mode}):h('section',{className:'p2-metric'},h('span',null,'Modo'),h('b',{style:{fontSize:'30px'}},'Participativo'))))) }
function Status({title,text,onReset}){return h('div',{className:'p2-app'},h('main',{className:'p2-main'},h('section',{className:'p2-panel p2-status'},logo(),h('span',{className:'p2-kicker'},'Projection 2.x'),h('h1',null,title),h('p',null,text),onReset?h('button',{className:'p2-btn',onClick:onReset},'Abrir otra sesión'):null))) }
function App(){const[code,setCode]=useCode(),[active,setActive]=useState(code.length===6),[state,setState]=useState(null),[error,setError]=useState(''),[tick,setTick]=useState(0);useEffect(()=>{if(!active)return;let disposed=false;let channel=null;const sync=async()=>{try{const x=await loadProjection(code);if(disposed)return;if(!x){setError('Código no encontrado.');setState(null);return}setError('');setState(x);if(!channel&&x.s?.session_id){channel=sb.channel(`projection-v2-${x.s.session_id}`).on('postgres_changes',{event:'*',schema:'public',table:'v2_sessions',filter:`id=eq.${x.s.session_id}`},sync).on('postgres_changes',{event:'*',schema:'public',table:'v2_questions',filter:`session_id=eq.${x.s.session_id}`},sync).on('postgres_changes',{event:'*',schema:'public',table:'v2_participants',filter:`session_id=eq.${x.s.session_id}`},sync).on('postgres_changes',{event:'*',schema:'public',table:'v2_responses'},sync).subscribe()}}catch(e){if(!disposed)setError('Reconectando con la sesión…')}};sync();const poll=setInterval(sync,2500),clock=setInterval(()=>setTick(v=>v+1),500);return()=>{disposed=true;clearInterval(poll);clearInterval(clock);if(channel)void sb.removeChannel(channel)}},[active,code]);const open=()=>{if(code.length!==6)return;history.replaceState(null,'',`?code=${code}`);setActive(true)};const reset=()=>{history.replaceState(null,'','./');setState(null);setError('');setCode('');setActive(false)};if(!active)return h(Entry,{code,setCode,onOpen:open,error});if(error&&!state)return h(Status,{title:'Reconectando…',text:error,onReset:reset});if(state?.closed)return h(Status,{title:'Sesión finalizada',text:state.s?.title||'La clase terminó.',onReset:reset});if(!state)return h(Status,{title:'Conectando…',text:'Preparando la pantalla del aula.'});if(!state.q)return h(Lobby,{x:state,code});return h(Live,{x:state,code,tick})}

createRoot(document.getElementById('projectionApp')).render(h(App));
